### ISSUE TITLE
Pull in data automatically from CLDR

### ISSUE THREAD

**Issue by Munter** [mledoze/countries#108]
http://cldr.unicode.org/ has a lot of this information already, and curated to perfection.

You should probably automate the extraction of duplicate types of information.

https://github.com/papandreou/node-cldr might come in handy here

**Comment by srl295** [comment]
It's also available in Json format. Cc @jcemmons and @rxaviers

**Comment by rxaviers** [comment]
@srl295, thanks for cc'ing.

@Munter, for CLDR in the JSON format use [Unicode's official bindings](http://cldr.unicode.org/index/cldr-spec/json). Files are here: [json.zip](http://www.unicode.org/Public/cldr/26.0.1/json-full.zip) and [json-full.zip](http://www.unicode.org/Public/cldr/26.0.1/json-full.zip). For npm and bower helpers, use `npm install cldr-data` ([more info](https://github.com/rxaviers/cldr-data-npm)) or `bower install cldr-data` ([more info](https://github.com/rxaviers/cldr-data-bower)).

**Comment by mledoze** [comment]
That's still a good and relevant idea, but I haven't had the time to work on it. I'll close this issue for the moment, but keep the idea in the To-do section in the Readme.

Thank you guys for the suggestion.
