### ISSUE TITLE
Proposal: Get 1000 likes! XD

### ISSUE THREAD

**Issue by herrniemand** [mledoze/countries#110]
![_007](https://cloud.githubusercontent.com/assets/1636116/6046705/5d37b0fa-ad09-11e4-8763-3a6bc79ecc7b.png)
 I think it is important issue, that we are three likes away from thousand! Somebody should fix it! XD

**Comment by herrniemand** [comment]
2 more to go*)

**Comment by herrniemand** [comment]
![_008](https://cloud.githubusercontent.com/assets/1636116/6050350/9e84bd22-ad23-11e4-943f-8f025bd31abd.png)
I guess this issue solved XD
Happy 1000+ stars! :beers:  for everyone!

**Comment by mledoze** [comment]
Congratulations and thank you to all who contributed!!! :smiley: 

https://github.com/mledoze/countries/graphs/contributors
