### ISSUE TITLE
Country borders (coordinates)

### ISSUE THREAD

**Issue by Wikunia** [mledoze/countries#119]
Hey guys,

do you want to integrate the border coordinates for each country?
Something like this stuff: http://github.wikunia.de/Table2Chart/getFunctions/layer.php?country=Australia

**Comment by herrniemand** [comment]
@Wikunia countries project have countries outlying in [data folder] (https://github.com/mledoze/countries/tree/master/data). We store data in GeoJSON format.  Example https://github.com/mledoze/countries/blob/master/data/aze.geo.json

**Comment by Wikunia** [comment]
@herrniemand oh didn't see it. Thanks!

**Comment by herrniemand** [comment]
@Wikunia *)
