### ISSUE TITLE
countries was not injected in your file

### ISSUE THREAD

**Issue by Shawful** [mledoze/countries#129]
When using yeoman's <code>grunt serve</code> command, my command prompt tells me that "countries was not injected in your file. Please go take a look in 'app/bower_components/countries' for the file you need, then manually include it in your file."

Any idea what's going on?

**Comment by Shawful** [comment]
Similar issue here?

Font-awesome issue:
https://github.com/stephenplusplus/grunt-wiredep/issues/25

**Comment by Shawful** [comment]
This might possibly be the cause:

Popcorn.js injection problem/solution:
http://stackoverflow.com/questions/21840776/popcorn-was-not-injected-in-your-file

**Comment by Shawful** [comment]
yes, adding the following property within the bower.json file of the project resolved the issue for me.

<code>"main":"./index.js",</code>

If I have time, I will add this to the open source code base.

**Comment by Shawful** [comment]
Acutally, I don't see the bower.json file - not sure how to proceed.

**Comment by mledoze** [comment]
> I don't see the bower.json file

@Shawful it's because this project has not yet been made available as a bower package. For the moment, it's only available as an [npm package](https://www.npmjs.com/package/world-countries)
