### ISSUE TITLE
Contradictory contribution rules?

### ISSUE THREAD

**Issue by cumanacr** [mledoze/countries#130]
Hi @mledoze I'm trying to merge upstream/master on #125 to keep it up to date.

So, I checked, README.md on [countries/dist](https://github.com/mledoze/countries/blob/master/dist/README.md) which says:  **"Do not commit any changes here"**

But, [CONTRIBUTING.md](https://github.com/mledoze/countries/blob/master/CONTRIBUTING.md), says:
"You can contribute to this project by simply adding or fixing data in countries.json. Before sending your pull request you can optionally rebuild the files in the dist folder using the countries.php script."

I know that it reads optionally, but, It "feels" confusing.

Am I giving it much importance?

**Comment by petert82** [comment]
I think the essence of this is: don't _only_ commit changes in the dist files. Those should always be generated from the non-dist countries data.

**Comment by herrniemand** [comment]
@cumanacr that is why there is line "This distribution folder contains generated data.". 

What happend previously is that people were doing changes into our dist data, so we had to reject their commits. That is why there is the message.

**Comment by mledoze** [comment]
@petert82 is right. We created this README.md to prevent contributions and/or fixes that were made only to the files in this directory and not in the master countries.json file. The correct process is to first modify the master file, and then regenerate the dist files using the conversion script.

**Comment by cumanacr** [comment]
@petert82 @herrniemand @mledoze thanks, roger that.

That's how I was doing it until now, so, no problem, CONTRIBUTING.md is clear.
But the doubt came when I read README.md on countries/dist.

Thanks again.
