### ISSUE TITLE
Multiple capitals

### ISSUE THREAD

**Issue by JacquesMarais** [mledoze/countries#132]
Allow some countries to have multiple capitals like South Africa has 3: Pretoria, Cape Town and Bloemfontein

**Comment by Newman101** [comment]
I think this can be sorted out - as far as I know, JSON supports multiple values for same key through arrays. 

http://stackoverflow.com/questions/17093180/store-multiple-values-in-single-key-in-json

**Comment by mledoze** [comment]
@JacquesMarais yes no problem. Would you mind sending a pull request with this modification?

**Comment by JacquesMarais** [comment]
Right, I sent a PR.

**Comment by JacquesMarais** [comment]
Please see the PR.

**Comment by mledoze** [comment]
@JacquesMarais yes I have not forget it, I'll do it as soon as I can. Thank you for your patience.
