### ISSUE TITLE
Solomon Islands Dollar

### ISSUE THREAD

**Issue by thomasschiet** [mledoze/countries#143]
The currency is listed as SDB instead of the correct SBD.

**Comment by mledoze** [comment]
@thomasschiet thank you for this, @DraperStudio sent a pull request #144, and it has been merged.

**Comment by MrGrabazu** [comment]
Hi, there, it remains SDB in commited generated data, so has it been really fixed ?
See : [Solomon Island Dollar](https://en.wikipedia.org/wiki/Solomon_Islands_dollar)

Thanks
