### ISSUE TITLE
South Georgia and the South Sandwich Islands

### ISSUE THREAD

**Issue by CIRCLE73** [mledoze/countries#146]
South Georgia and the South Sandwich Islands are not a country of South America. 
It is a country from Antarctica.
http://www.newworldencyclopedia.org/entry/List_of_countries_by_continent#Antarctica

**Comment by herrniemand** [comment]
@CIRCLE73 No. They are not. But they are "British overseas territory" and so "theoretically" if they would have population they would be represented as separate object of international law. They have even separate iso code "gs".
