### ISSUE TITLE
Remove sub attribute.

### ISSUE THREAD

**Issue by thefabulousdev** [mledoze/countries#148]
I want to remove the countries name.native attribute on the output, is it possible to remove sub attributes?

**Comment by herrniemand** [comment]
@thefabulousdev unless you just remove with script. P.S. Give me a day and I will write you one.

**Comment by thefabulousdev** [comment]
Thanks for the quick reply, just wondering if I would be able to do it out of the box, I had already contemplated that I would probably have to write a script so I'll do it no problem , thanks for offering anyways.

**Comment by herrniemand** [comment]
@thefabulousdev might want to look at that https://github.com/herrniemand/countries-dev

**Comment by mledoze** [comment]
@thefabulousdev for the moment it is not possible. You can only select a list of top-level fields that you want to include in the generated files.

**Comment by Ramblurr** [comment]
@mledoze  Any plans to add this feature?

@herrjemand I don't see a script in your repo that does this, or am I missing it?

**Comment by mledoze** [comment]
@Ramblurr this feature is not planned yet but I'll add it to my to-do list.
