### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by coding-sunshine** [mledoze/countries#151]
Is there any way to get timezone list of countries?

**Comment by herrniemand** [comment]
@coding-sunshine we have decided not to add timezones yet, as they tend to change too frequently.
Please read this thread https://github.com/mledoze/countries/pull/106.
But you can get latest timezone db from http://timezonedb.com/download

**Comment by herrniemand** [comment]
@coding-sunshine check this out as well https://github.com/AnatoliyGatt/timezonedb-node

**Comment by coding-sunshine** [comment]
Thanks

**Comment by herrniemand** [comment]
@coding-sunshine *)
