### ISSUE TITLE
Tax rates key proposal

### ISSUE THREAD

**Issue by toubou91** [mledoze/countries#153]
What about providing also a tax rates key?

The following links might seem helpful:
<ul><li><a href="https://en.wikipedia.org/wiki/List_of_countries_by_tax_rates">wiki tax rates</a></li><li><a href="https://euvatrates.com/rates.json">EU VAT Rates Web Service<a/></li></ul>

**Comment by herrniemand** [comment]
Hey @toubou91. Thank you for you idea. 
Unfortunately tax-rates is quiet variable data, and so it would take too much resources to maintain. We had the same issues with population, and it ended up removed(https://github.com/mledoze/countries/issues/6#issuecomment-42322804).
In this project we are trying to maintain accurate, static basic information about countries, not the most widely defined. 
But thanks for the links. I will keep them for my future projects. *)

**Comment by toubou91** [comment]
Hello @herrniemand , not a problem at all. 
Actually, I just learned sth new; taxes use to vary in countries other than Greece, too, hah.

Cheers!

**Comment by herrniemand** [comment]
@toubou91 *)
