### ISSUE TITLE
Country bounds

### ISSUE THREAD

**Issue by StephanGeorg** [mledoze/countries#156]
A missing feature is the bounds (northeast and southwest) of the countries like [geonames.org](http://api.geonames.org/countryInfoJSON?lang=it&country=DE&username=demo).

**Comment by herrniemand** [comment]
@StephanGeorg I am not sure if this would be useful to the project. It might be too precise. Perhaps you mention this at our future plan discussion #6.

**Comment by mledoze** [comment]
@StephanGeorg yes this feature is missing, I thought it was not particularly useful. Maybe I'm wrong, so please propose this in #6, there might be a need for this.
