### ISSUE TITLE
Native names as list?

### ISSUE THREAD

**Issue by madsbrydegaard** [mledoze/countries#157]
Have you considered changing the native names into a list?

Use case example:
I want to output the native name in a list.
When iterating I should be able to reference the first native name.

Now its only possible to output the native name if I know which language code I want.

**Comment by herrniemand** [comment]
@madsbrydegaard Native languages object represented as object, as there could be more then one native language for the country, i.e. New Zealand with English, Maori, and so they are distinguished by the language code.
  
From another side, I don't see any technical problem to iterate through an object. Here is some examples how to iterate over native languages object:

JavaScript:
```javascript
var nativeLanguages = {
    "bar": {
        "official": "Republik Österreich",
        "common": "Österreich"
    }
}

var keys = Object.keys(nativeLanguages);

for (var i = nativeLanguages.length - 1; i >= 0; i--) {
    console.log(nativeLanguages[i].official)
};
```

Python
```python
nativeLanguages = {
    "bar": {
        "official": "Republik Österreich",
        "common": "Österreich"
    }
}

for language in nativeLanguages:
    print(language["official"])
```

PHP
```php
<?php
$json = '{
    "bar": {
        "official": "Republik Österreich",
        "common": "Österreich"
    }
}'

$nativeLanguages = json_decode($json);

foreach ($nativeLanguages as $key => $value) {
    echo $value['official'];
}

?>
```

For other examples please reffer to google and stackoverflow.
Here is link so you don't have to search http://lmgtfy.com/?q=How+to+iterate+over+an+associative+array%2C+list%2C+object 

Best regards. Ackermann Yuriy

**Comment by madsbrydegaard** [comment]
Gotcha

**Comment by herrniemand** [comment]
@madsbrydegaard  *) Happy to help
