### ISSUE TITLE
Missing BQ country code

### ISSUE THREAD

**Issue by nevenavv** [mledoze/countries#158]
https://en.wikipedia.org/wiki/Caribbean_Netherlands

**Comment by herrniemand** [comment]
@nevenavv Caribbean Netherlands dissolute in 2010(https://en.wikipedia.org/wiki/Dissolution_of_the_Netherlands_Antilles). Please refer to #150.

**Comment by mledoze** [comment]
@nevenavv please see this comment: https://github.com/mledoze/countries/issues/150#issuecomment-136358570.
