### ISSUE TITLE
Change Kosovo alpha-3 ISO code from KOS to UNK.

### ISSUE THREAD

**Issue by herrniemand** [mledoze/countries#159]
As @hackel found out from https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3, 
"UNK identifies Kosovo residents to whom travel documents were issued by the United Nations Interim Administration in Kosovo (UNMIK)". I will contact UNMIK first, and confirm such information, first.

**Comment by mledoze** [comment]
@herrniemand could you please send a pull request?

**Comment by herrniemand** [comment]
Sure. As soon as i get to office
7 дек. 2015 г. 11:28 PM пользователь "Mohammed Le Doze" <
notifications@github.com> написал:
