### ISSUE TITLE
Suggestion: make demonym translatable 

### ISSUE THREAD

**Issue by jeffrico** [mledoze/countries#165]
I think it would be just wonderful if demonyms would be translatable...
Just an opinion...

**Comment by mledoze** [comment]
@jeffrico yes that would be a good idea. Do you have a preferred language with which you would like to start?

**Comment by mledoze** [comment]
> Do you have a preferred language with which you would like to start? 

ping @jeffrico :wink:

**Comment by israelroldan** [comment]
I would like to contribute with Spanish and Dutch. 

Before applying the patch, does the following schema looks ok to you?
```
{
    ...
    "denonym": {
        "eng": "American",
        "spa": "Estadounidense",
        "nld": "Amerikaan"
    },
    ...
}
```

**Comment by mledoze** [comment]
@israelroldan OK for me.

**Comment by davividal** [comment]
Shouldn't you use ISO codes?

**Comment by herrjemand** [comment]
@davividal they are ISO 639-2/3 alpha3 language codes

**Comment by WaldoJeffers** [comment]
Hello, any updates on this?

**Comment by mledoze** [comment]
ping @jeffrico :)

**Comment by ottsch** [comment]
Any ideas how to handle irregular plural, female/male variants (as in German)?

Also, there are different possible demonyms sometimes like here:

- Antiguayen, Antiguayenne; 
- Antiguais, Antiguaise; 
- Antiguais-et-Barbudien, Antiguaise-et-Barbudienne

([source](http://66.46.185.79/bdl/gabarit_bdl.asp?Th=2&t1=&id=1941))

**Comment by alexsegura** [comment]
Since #343 has been merged, I think this can be closed? @mledoze

**Comment by mledoze** [comment]
Sure.
