### ISSUE TITLE
Languages in JSON

### ISSUE THREAD

**Issue by newerton** [mledoze/countries#169]
Why not use the ISO 639?

**Comment by herrniemand** [comment]
@newerton We are using three-letter ISO 639-3 language code

**Comment by newerton** [comment]
@herrniemand The correct, would not 2 letter?

Example of my Country.
Portuguese Brazil is 'pt-BR', not 'por'.
'pt' is Portuguese and 'BR' of Brazil.

In the case of '[por] => 'Portuguese'', I can not identify whether it is Portuguese from Portugal or Brazil.

In Portugal is 'pt' or 'pt-PT'.
'pt' is Portuguese and 'PT' of Portugal.

Sorry my English!

Tranks!

**Comment by newerton** [comment]
Just one correction, I am developing a database for languages that are supported by browsers, and 2 letters of the final, I'm taking the field 'CCA2'.

Thanks!

**Comment by herrniemand** [comment]
@newerton CCA2 should not be used for as ISO639. Despite their similarity there is a lot of difference. 
For instance. If you get person from Switzerland(ch), which of the 7 languages should you use? Or Austria:(at), ho would you convert that to German?

You better be using user prefer language, and then using that convert to ISO639-3

**Comment by herrniemand** [comment]
@newerton In countries project we decided to use ISO639-3, due to limitations of ISO639-2 codes. A lot of languages are not represented in ISO639-2 due to its size limitation.

**Comment by herrniemand** [comment]
@newerton good example [Serbo-Croatian](https://en.wikipedia.org/wiki/Serbo-Croatian) language, that does not even have Alpha-2 code.

**Comment by newerton** [comment]
Understand!

The problem is that browsers work with ISO 639-2 and ISO 3166.
I will use the Google Maps API, for my purpose!

Thanks for the help!

**Comment by herrniemand** [comment]
@newerton happy to help*)
