### ISSUE TITLE
UTF-8 character format of the source file countries.json

### ISSUE THREAD

**Issue by guoyunhe** [mledoze/countries#174]
Since countries.json is used for editing and contribution, it should be easy to read for human. But now it is written like this:

```
"jpn": {"official": "\u30e9\u30c8\u30d3\u30a2\u5171\u548c\u56fd", "common": "\u30e9\u30c8\u30d3\u30a2"},
```

Without special tools, people cannot read this or write their own. Should it just use unescaped JSON? Anyway you can export escaped JSON in dist folder.

Thanks!

**Comment by herrniemand** [comment]
@guoyunhe The reason for this is that for JSON to be valid, non ASCII chars have to unicode escaped.

**Comment by herrniemand** [comment]
@guoyunhe How ever, you are right. Maybe we do need to make main file non escaped, since it is mainly used for editing. 
@mledoze what do you think?

**Comment by guoyunhe** [comment]
It depends on the JSON parser we used. Today, most of JSON parsers can decode unescaped JSON. Since this project uses PHP to parser JSON data, and PHP's `json_decode()` function can decode unescaped JSON, I think it will be okay.

Here is an example:

```php
<?php
$json = '{"a":1,"b":2,"c":3,"d":4,"e":"你好"}';

var_dump(json_decode($json));
var_dump(json_decode($json, true));

```

Output:

```
object(stdClass)#1 (5) {
  ["a"]=>
  int(1)
  ["b"]=>
  int(2)
  ["c"]=>
  int(3)
  ["d"]=>
  int(4)
  ["e"]=>
  string(6) "你好"
}
array(5) {
  ["a"]=>
  int(1)
  ["b"]=>
  int(2)
  ["c"]=>
  int(3)
  ["d"]=>
  int(4)
  ["e"]=>
  string(6) "你好"
}
```

**Comment by mledoze** [comment]
> @mledoze what do you think?

I prefer to keep the current encoding especially because this file is used for editing and contributing. The `countries.json` file contains many right-to-left strings and not all text editors handle these correctly.
