### ISSUE TITLE
Chinese language code and name

### ISSUE THREAD

**Issue by guoyunhe** [mledoze/countries#175]
Here are a lot of "cmn" and "zho" for Chinese language. "cmn" is only for Mandarin Chinese, but "zho" is for all Chinese languages. Since here is no other varieties used, we can just use only one, "zho" or "cmn", rather than mixing both.

Current:
```
"name": {
	"common": "Taiwan",
	"official": "Republic of China (Taiwan)",
	"native": {
		"cmn": {
			"official": "\u4e2d\u534e\u6c11\u56fd",
			"common": "\u81fa\u7063"
		}
	}
},

...

"name": {
	"common": "Hong Kong",
	"official": "Hong Kong Special Administrative Region of the People's Republic of China",
	"native": {
		"eng": {
			"official": "Hong Kong Special Administrative Region of the People's Republic of China",
			"common": "Hong Kong"
		},
		"zho": {
			"official": "\u9999\u6e2f\u4e2d\u56fd\u7279\u522b\u884c\u653f\u533a\u7684\u4eba\u6c11\u5171\u548c\u56fd",
			"common": "\u9999\u6e2f"
		}
	}
},
```

Suggestion, replace all "cmn" with "zho":
```
"name": {
	"common": "Taiwan",
	"official": "Republic of China (Taiwan)",
	"native": {
		"zho": {
			"official": "\u4e2d\u534e\u6c11\u56fd",
			"common": "\u81fa\u7063"
		}
	}
},

...

"name": {
	"common": "Hong Kong",
	"official": "Hong Kong Special Administrative Region of the People's Republic of China",
	"native": {
		"eng": {
			"official": "Hong Kong Special Administrative Region of the People's Republic of China",
			"common": "Hong Kong"
		},
		"zho": {
			"official": "\u9999\u6e2f\u4e2d\u56fd\u7279\u522b\u884c\u653f\u533a\u7684\u4eba\u6c11\u5171\u548c\u56fd",
			"common": "\u9999\u6e2f"
		}
	}
},
```

**Comment by herrniemand** [comment]
@guoyunhe As a developer of the countries.json language system, I give you my :+1: to perform the changes.

**Comment by guoyunhe** [comment]
OK, I will make a pull request later.

I will keep "languages" properties still `"cmn": "Mandarin"`, since official languages are indeed Mandarin not general Chinese. But language code in "name" and "translations" properties will be changed to "zho".

**Comment by herrniemand** [comment]
@guoyunhe Languages is corresponds directly to name object. So could you please change language codes in languages objects as well, just keep the name. i.e. `"cmn": "Mandarin"` -> `"zho": "Mandarin"`

**Comment by guoyunhe** [comment]
I think the valid code-name match is `"zho": "Chinese"`, I can also change it to this if others agree.

**Comment by herrniemand** [comment]
@guoyunhe `zho` is ISO 639-3/2 code for Chinese language. `cmn` is ISO 639-3 is individual code for Mandarin language variation of Chinese. So `zho` will be enough sufficient,
