### ISSUE TITLE
php runtime error

### ISSUE THREAD

**Issue by guoyunhe** [mledoze/countries#176]
```
$ composer install
$ php countries.php convert

PHP Catchable fatal error:  Argument 1 passed to MLD\Converter\AbstractConverter::__construct() must be of the type array, null given, called in /home/sign/git/countries/src/MLD/Console/Command/ExportCommand.php on line 84 and defined in /home/sign/git/countries/src/MLD/Converter/AbstractConverter.php on line 24
```

Since composer.lock file doesn't exist, composer might install newer version packages.

**Comment by mledoze** [comment]
Hello @guoyunhe, which PHP version do you use?

**Comment by mledoze** [comment]
I ran the same commands as you and it works.
Here are the versions I have after a fresh installs:
```
symfony/console           v3.0.6 Symfony Console Component
symfony/polyfill-mbstring v1.2.0 Symfony polyfill for the Mbstring extension
symfony/yaml              v3.0.6 Symfony Yaml Component
```

I'll soon commit a composer.lock file to prevent these kind of issues.

**Comment by mledoze** [comment]
Hello @guoyunhe, I've added a `composer.lock` file. Could you please tell me if you still have the runtime error?
