### ISSUE TITLE
Map Projection

### ISSUE THREAD

**Issue by pkostov** [mledoze/countries#178]
It is not quite a problem with the data itself and I'm sorry if my question is redundant, but I tried to find information about the map projection of the geographic data in the geojson files and the latitude/longitude centroids of the countries.

Could the map projection be "Web Mercator" (EPSG:3857) - the same Google uses? It might be interesting for other people that this is put somewhere with the code.

**Comment by herrjemand** [comment]
Hey @pkostov. A map projection is a systematic transformation of the latitudes and longitudes of locations on the surface of a sphere or an ellipsoid into locations on a plane.

Think about map projections like a different geometric objects, and GeoJSON data like a stretch fabric that you stretch over it. When you stretch fabric over ellipsoid, relative location of points on the fabric, does not change.

Same with GeoJSON coordinates. They are relative location to the imaginary center of earth. Different projections does not change data, and so it is not stored in GeoJSON files. It is setting of the map you are using. If you want to play with different projections, try Liflet library.
