### ISSUE TITLE
Default/official language

### ISSUE THREAD

**Issue by rootwalla** [mledoze/countries#181]
The country model lacks an official or primary language property.
Without one, the first language in the set becomes it by implication.
This is not always correct or respected.

As in the case of Italy, where bavarian german is in first place and not italian.

**Comment by herrjemand** [comment]
@rootwalla There is no such a concept as official language. There is official `languages`. For example: New Zealand official languages are English and Maori(and Sign Language), but majority speaks English. If we were just leave English as official language, that would just be majoritarian decision, and not represent the official status.

As to Italy and few other countries: During implementation of language object, for some of the countries, I went too specific. Bavarian German is official language in South Tyrol, but not the Italy in total. I will have to go through and fix it.

**Comment by rootwalla** [comment]
OK, then the language array should (try to) obey most spoken order.

thanks

**Comment by herrjemand** [comment]
@rootwalla It is easy to say, and hard to implement, hard to maintain as well. Very excessive, and useless information. 

As addition, it is not exactly an issue in Countries project.

**Comment by jurchiks** [comment]
I'm actually trying to find a list of countries with their most commonly spoken language myself, but I can't find anything like that. Looks like I will have to go through all 250+ countries manually and look it all up.
If the national language array would contain the languages in order of popularity, I could have used your dataset, but since it apparently doesn't...

**Comment by bfelbo** [comment]
@jurchiks Did you ever find or create this? We also need a list of the most commonly spoken languages in each country (rough approximation or outdated order is fine).

**Comment by jurchiks** [comment]
I did it manually, but  in many cases there aren't actually such generic "most commonly spoken languages"; for many countries, they are split by region, or by usage (legal vs colloquial), etc.

**Comment by bfelbo** [comment]
Okay, that makes sense. Could you share your list? That would be really appreciated!

**Comment by jurchiks** [comment]
Unfortunately I don't have access to the database anymore.
