### ISSUE TITLE
Thanks :)

### ISSUE THREAD

**Issue by nerik** [mledoze/countries#185]
This lib is very useful, and it's a pleasure using it. Thanks for your work.

**Comment by herrjemand** [comment]
@nerik XD

**Comment by mledoze** [comment]
@nerik amazing PR, thank you for your support, it's greatly appreciated :) Would you care to share how you use this lib?
Thanks.

**Comment by nerik** [comment]
I'm working on a package for the Atom editor to interact with the Carto API (Carto is a set of APIs and tools for mapping and geographical analysis). 
One of the features is geocoding inside Atom, which requires turning locations strings (ie Dublin, Ireland) into SQL requests, choosing the right SQL function for each entity type (country, city, address, IP, postal code, etc). This is done via [carto-geocoding-sql](https://github.com/nerik/carto-geocoding-sql), which uses this lib to autoselect countries, whatever the locale is.
So, again: 👍
