### ISSUE TITLE
Measurement units for every countries with symbols

### ISSUE THREAD

**Issue by AlessandroCorradini** [mledoze/countries#187]
Could you add the measurement units for each country? Example length, weight, temperature and others with the symbols of the respective units.

**Comment by herrjemand** [comment]
@AlessandroCorradini You mean metric/nonmetric?

**Comment by herrjemand** [comment]
@AlessandroCorradini I mean it is veeeeeery simple fix, by just adding "metric": true, and fixing it for three countries to false

**Comment by herrjemand** [comment]
@AlessandroCorradini but personally I am not sure if that would be useful. What do you think @mledoze?

**Comment by jjlharrison** [comment]
@herrjemand: It's a bit more complicated than a boolean. The UK for example uses a mix of imperial and metric for different purposes.

**Comment by AlessandroCorradini** [comment]
No, I mean like this:
// for ITA (I'm Italian)
"measurement_units":  [
       "lenght": ["mm", "cm", "m"] // from small to big, but I could be useful just "m"
       "weight": ["mg", "gr", "kg"], // but I could be useful just "kg"
       "temperature": "C"
....... and others
]

If a user choose a country, you can get the default measurement units and set them into the app and apply the appropriate conversions with a function. It's useful for international app.

**Comment by herrjemand** [comment]
@AlessandroCorradini 
IMHO I don't like this this implementation. It is large, complicated, detailed, and very hard to implement and maintain.

@jjlharrison 
I know a lot of countries have their own systems as well, like Japanese Shakkanho
Might be

`"units": ["metric", "imperial"]`

That will give basic understanding on what the state of the things.

## Personally
I have can see potential use of such information, but I am against making system complicated. We need to keep it simple.

Need to see what @mledoze will say.

**Comment by jjlharrison** [comment]
I personally would find this information very useful. Some projects I work on need to know whether to use miles or kilometres for distances depending on the target market.

This is a common problem when localising software.

**Comment by AlessandroCorradini** [comment]
Yes, it's too complicated :D
For simplicity you could add just one unit for each properties, like:

"length": "m", 
"weight":  "kg", 
"temperature": "C"

it's more simple and equally useful :)

**Comment by herrjemand** [comment]
@AlessandroCorradini That is still complicated
```
"length": "m", 
"weight": "kg", 
"temperature": "C"
```

Its complicated, detailed and underrepresented. 

Quoting @jjlharrison 
> The UK for example uses a mix of imperial and metric for different purposes.

So that's mean this approach does no represents the real picture.

Additionally it is detailed.

**Comment by mledoze** [comment]
@AlessandroCorradini I'm sorry but I don't think that measurement units are a good fit for this project. Its purpose is to provide a simple and generic dataset about countries, not to include every country data possible. Thank you for your proposition though.

I'm sorry for the late answer.
