### ISSUE TITLE
Add TopoJSON files

### ISSUE THREAD

**Issue by tanc** [mledoze/countries#199]
Firstly, thanks for this repository, very useful.

Would you consider adding TopoJSON files alongside the GeoJSON files in the data directory? TopoJSON are smaller and more efficient.

**Comment by mledoze** [comment]
Hello @tanc 

> thanks for this repository, very useful.
you're welcome :)

> Would you consider adding TopoJSON files alongside the GeoJSON files in the data directory? 
Yes, that's a great idea! The current GeoJSON data comes from http://www.naturalearthdata.com/, will you be able to create TopoJSON files from this data?

**Comment by tanc** [comment]
Sure! Happy to give it a try. Should I fork and add them as a pull request?

**Comment by mledoze** [comment]
> Sure! Happy to give it a try. Should I fork and add them as a pull request?

Yes please.

**Comment by tanc** [comment]
I've converted all the GeoJSON data files into TopoJSON and tested a few, some simple and some very big and complex (Canada) and they are rendering really nicely in Leaflet and much faster.

Pull request has been submitted: #200

**Comment by mledoze** [comment]
#200 has been merged. Thank you @tanc.
