### ISSUE TITLE
Add travis-ci for json lint

### ISSUE THREAD

**Issue by paulvollmer** [mledoze/countries#201]
this can be easy setup by a node.js jsonlint configration like the following

```
language: node_js
node_js: node
install: npm install jsonlint -g
script: jsonlint countries.json 
```

_(no warranty for the snippet)_

vote for it, and we can setup linters for the other languages (xml, yaml, php etc.)

**Comment by mledoze** [comment]
@paulvollmer good idea! Would you be able to provide a correct configuration snippet please?

**Comment by mledoze** [comment]
Merged via a1f37a3e6d79ff8cdfcdea6442ab05b87c8cdec7, thank you for your help @paulvollmer

**Comment by Fevix** [comment]
Sorry for necro, but is there a way I can use this to lint all files except those on a blacklist? (In my case, lint everything that's not .png or .lua)

**Comment by mledoze** [comment]
@Fevix what do you mean by "lint all files"? If you look here https://github.com/mledoze/countries/blob/master/ci/test.sh, you'll see that we only lint JSON files, so .png and .lua files are excluded.

**Comment by Fevix** [comment]
I make a mod for Starbound which uses mostly json but the files aren't
named .json, they're named stuff like .item and .object. They are purely
json though

I've found a solution already though, thanks to Reddit.
