### ISSUE TITLE
Add geographic centre

### ISSUE THREAD

**Issue by tanc** [mledoze/countries#206]
Some countries have territories a long way away from their main landmass so when trying to find the centre of the country using a bounding box in leaflet (for example), the centre is way off where you'd expect to find it. This makes it hard to place labels (country name etc) where the user is expecting to see them.

There seems to be a fairly comprehensive list of geographic centres provided by http://gothos.info/resources/

It would be great to see these lat lng values integrated into the dataset.

**Comment by tanc** [comment]
I feel like a fool! The geographic centres are already there!

**Comment by mledoze** [comment]
@tanc no problem :)
