### ISSUE TITLE
unidirectional borders?

### ISSUE THREAD

**Issue by rd--** [mledoze/countries#208]
Hello

Thanks very kindly for the excellent data set.

I've noticed that there are some borders that are indicated only in one direction?

ie. CYP has GBR as a border, but GBR doesn't have CYP.

The set of these "uni-directional" borders is:

(CYP,GBR) (IND,AFG) (NPL,CHN) (PSE,ISR) (PSE,EGY) (PSE,JOR) (SDN,TCD) (TCD,SSD)

There are no borders at (IND,AFG) or (TCD,SSD), these should be deleted?

There are borders at (NPL,CHN) and (SDN,TCD), so (CHN,NPL) and (TCD,SDN) should be added?

PSE does border ISR, EGY and JOR, and it is in the data set, so I guess these should be added?

CYP borders Akrotiri and Dhekelia, which is a British Overseas Territory, but it is not in the data set.

There are various ways to think about this, the diff attached below deletes (CPY,GBR) and makes the other changes mentioned.

Thanks again,

rd

[countries-borders-rd.txt](https://github.com/mledoze/countries/files/829138/countries-borders-rd.txt)

**Comment by mledoze** [comment]
Hello @rd--, thank you for raising this issue. I'll take your fixes and merge them into the project.
