### ISSUE TITLE
Include address_format from hexorx data?

### ISSUE THREAD

**Issue by drbyte** [mledoze/countries#209]
Given that you're already pulling region/subregion data from the @hexorx countries package, would you be willing to also include the address formats in that same dataset?
I think it's fairly static data.

I'm happy to help with contributing if you're willing to include it.

**Comment by mledoze** [comment]
I'm okay with that. Could you propose a format in JSON?

**Comment by drbyte** [comment]
The data from hexorx has `address_format` as a (optional) single entry per country record.

I would think that if we simple brought it in as a string value it would be fine. ie: keep the current `Liquid` markup, as it can be easily parsed when used in production. 

So the result would be akin to:

```diff
	"currency": ["EUR"],
	"callingCode": ["43"],
	"capital": "Vienna",
+	"address_format": "{{recipient}}\n{{street}}\n{{city}} {{region}} {{postalcode}}\n{{country}}",
	"altSpellings": ["AT", "Osterreich", "Oesterreich"],
	"region": "Europe",
	"subregion": "Western Europe",
```

I may be missing something, but how are you reading data in from other sources? Or was it just a one-time import and now manually maintaining static files? I don't see an import generator ... just export. Or maybe I haven't had enough coffee yet today :)

**Comment by mledoze** [comment]
>I would think that if we simple brought it in as a string value it would be fine. ie: keep the current Liquid markup, as it can be easily parsed when used in production.

I like the liquid markup but I'm not fond of `\n` characters in the middle of the string. We need to think about a better solution...

> I may be missing something, but how are you reading data in from other sources?

You're not missing anything :) there are no import scripts because the main `countries.json` was crafted with my own little hands (and those of the contributors, of course!), but since it's static data, there was no need to develop import scripts.

**Comment by drbyte** [comment]
> was crafted with my own little hands

Haha! A labour of love ;)

**Comment by drbyte** [comment]
> I like the liquid markup but I'm not fond of \n characters in the middle of the string. We need to think about a better solution...

I wouldn't be bothered if we used `{{cr}}` instead of `\n` and people can substitute that with their preferred "carriage-return" markup.  Or is "carriage-return" too 80's sounding?

**Comment by kmpoppe** [comment]
I'm a little late to the party, but a) I'd like the address formats in the json and b) I don't think `{{cr}}` is too 80's ... VisualBasic also uses `vbCrLf` for carriage-return/line-feed, so I think that's nothing to worry about!

**Comment by mledoze** [comment]
@kmpoppe you're not late to the party :) I'm okay with the `{{cr}}` proposal. @drbyte are you still willing to work on this?

**Comment by drbyte** [comment]
I'm still interested in seeing this done. 
It'll be several weeks before I can tackle it though, especially if it all must be coded by hand instead of imported.

**Comment by mledoze** [comment]
I understand. I will try to fetch the data directly from hexorx data and add it in this project.
