### ISSUE TITLE
Bonaire, Sint Eustatius and Saba missing

### ISSUE THREAD

**Issue by tflori** [mledoze/countries#210]
a country is missing... https://en.wikipedia.org/wiki/ISO_3166-1 BQ: Bonaire, Sint Eustatius and Saba

**Comment by herrjemand** [comment]
@tflori Please refer to: https://en.wikipedia.org/wiki/Dissolution_of_the_Netherlands_Antilles

**Comment by herrjemand** [comment]
Also refer to #150

**Comment by tflori** [comment]
hmm thanks for the info.

So what to do when I want them in my list? Do I have to call extra feeds?

**Comment by herrjemand** [comment]
Jup. Bonaire not an independent state under the crown of the 'Kingdom of the Netherlands', like Aruba, Curacao and Sint-Maarten, but a city in a country of Netherlands. 

Useful video: https://www.youtube.com/watch?v=eE_IUPInEuc

**Comment by tflori** [comment]
thx @herrjemand

**Comment by herrjemand** [comment]
@tflori Happy to help*)
