### ISSUE TITLE
Wrong Russian translation for Mexico

### ISSUE THREAD

**Issue by skornev** [mledoze/countries#227]
"Мексиканских Соединенных Штатов" should be "Мексиканские Соединённые Штаты"
https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%BA%D1%81%D0%B8%D0%BA%D0%B0

**Comment by herrjemand** [comment]
@skornev Approve. Thanks for mentioning*)

**Comment by mledoze** [comment]
Thank you for raising this issue. Could you please send a pull request with the fix?
