### ISSUE TITLE
Cocos Islands should be added for Cocos (Keeling) Islands

### ISSUE THREAD

**Issue by ocalypse** [mledoze/countries#237]
https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands

While there is indeed an unrelated "Cocos Island" (https://en.wikipedia.org/wiki/Cocos_Island), the plural "Cocos Islands" is an alternative name for Cocos (Keeling) Island.

I would suggest adding it to the "altSpelling" column.

As should maybe "Keeling Islands". Those were the names before they made the dual name official.

**Comment by mledoze** [comment]
@ocalypse thank you for this, I did this fix and it's merged.
