### ISSUE TITLE
Great compilation, but needs Localé

### ISSUE THREAD

**Issue by chiemekailo** [mledoze/countries#241]
Hi.
This is a great collection. However, I was appalled to find that it does not have localé (e.g. en-GB).

**Comment by herrjemand** [comment]
Hey @chiemekailo. We don't IETF language codes, but instead alpha-3 ISO codes for language tags.

**Comment by mledoze** [comment]
Hello @chiemekailo, thank you for your proposition but IETF language codes are not included in this dataset because codes likes `en-GB` which consist of a language code and a regional code, create too many combinations.

**Comment by chiemekailo** [comment]
> Hello @chiemekailo, thank you for your proposition but IETF language codes are not included in this dataset because codes likes `en-GB` which consist of a language code and a regional code, create too many combinations.

Thanks @mledoze and @herrjemand. I’m using it as-is okay.

**Comment by mledoze** [comment]
You're welcome @chiemekailo :slightly_smiling_face:
