### ISSUE TITLE
Bug: XK (Kosovo) is not an officially assigned code element

### ISSUE THREAD

**Issue by blumk** [mledoze/countries#253]
According to [ISO 3166-1 alpha-2](https://www.iso.org/obp/ui/#iso:pub:PUB500001:en) XK is a 'User-assigned code element'. Kosovo does not have a ISO country code (without being political).

I recommend either removing the entry (thus sticking with ISO 3166-1) or extending the data set to include non compliant entries.

[Explanation](https://www.quora.com/Why-doesnt-Kosovo-have-its-own-ISO-country-code-when-it-is-already-eligible-for-it-it-is-member-of-IMF-and-UN-treats-it-as-a-territory-separate-from-Serbia)
 

**Proposal:**
a) remove entry
_or_
b) add "status" flag to every record:

| status |
| --- |
| officially assigned |
| unassigned |
| exceptionally reserved |
| indeterminately reserved |
| transitionally reserved |
| user-assigned |
| formerly used |

This change would make the data set compliant with ISO 3166.

[see Glossary ISO 3166](https://www.iso.org/glossary-for-iso-3166.html)
or [Search filter](https://www.iso.org/obp/ui/#search)

**Comment by mledoze** [comment]
@blumk should we close this PR now since the independence flag has been merged?

**Comment by blumk** [comment]
@mledoze I'd still like to add a status flag `officially assigned` to every record, except Kosovo (`user-assigned`). That would allow for proper filtering of the dataset. Will provide a PR this week.
