### ISSUE TITLE
Bug: Missing ISO 3166-2:BQ (Bonaire, Sint Eustatius and Saba)

### ISSUE THREAD

**Issue by blumk** [mledoze/countries#254]
[ISO 3166-2:BQ](https://en.wikipedia.org/wiki/ISO_3166-2:BQ) is missing from the list.

I'm aware that these three islands are not independent countries, nevertheless they are treated as a dependent country according to ISO-3166-1.

I've created an issue #252 (include 'independent' flag) that would help filtering the data set.

I recommend keeping this data set compliant with ISO-3166-1.

**Comment by mledoze** [comment]
@blumk the data for these three islands is not messing from this dataset.

Please refer to this comment for more info: https://github.com/mledoze/countries/issues/150#issuecomment-136358570

**Comment by blumk** [comment]
@mledoze ISO 3166 assigns a country code to these islands with `independent=no`, [see 3166:BQ](https://www.iso.org/obp/ui/#iso:code:3166:BQ).

There are 194 independent countries listed in the standard and 55 dependent countries. I agree it seems odd to add this record, however not adding this record would start the discussion which of the 55 dependent countries should be included in the list (right now the dataset contains only 53 records).

I'd prefer to keep the dataset aligned with ISO 3166 and let the consumer of the dataset decide, which records to use (by providing filters).
