### ISSUE TITLE
Bug: Missing ISO 3166-2:SH (Saint Helena, Ascension and Tristan da Cunha)

### ISSUE THREAD

**Issue by blumk** [mledoze/countries#255]
[ISO 3166-2:SH](https://en.wikipedia.org/wiki/ISO_3166-2:SH) is missing from the list.

I'm aware that these islands are not independent countries, nevertheless they are treated as a dependent country according to ISO-3166-1.

I've created an issue #252 (include 'independent' flag) that would help filtering the data set.

I recommend keeping this data set compliant with ISO-3166-1.

**Comment by mledoze** [comment]
@blumk the data is not missing, it's just in a different place :)

Please see this issue for more info: https://github.com/mledoze/countries/issues/93

**Comment by blumk** [comment]
@mledoze see my comment on #254. I believe aligning the dataset with ISO 3166 is the better solution.

Quoting [ISO](https://www.iso.org/home.html):
> When the world agrees

I personally might not agree with every entry in the ISO standard, I do however believe in a standard that everyone agrees to (and then override the standard at my own risk in my application when needed).

[3166:SH](https://www.iso.org/obp/ui/#iso:code:3166:SH)
[Wikipedia](https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha)

**Comment by blumk** [comment]
I took a closer look at this issue:

The parent record [3166:SH](https://www.iso.org/obp/ui/#iso:code:3166:SH) should be included in the `contries.json` as it is a `British Overseas Territory` (like other territories).

The record contains three islands (parts) and each of them should have a `divisions` record in the `data` folder. Since almost every country has subdivisions (states, departements, regions, ...) I'd say this is out of scope for this project, see [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2). (There are over 4000 subdivisions.)

[Wikipedia](https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha)

**Comment by mledoze** [comment]
@blumk I am not so sure about what you are proposing?

**Comment by blumk** [comment]
@mledoze I'd like to add `ISO 3166-2:SH (Saint Helena, Ascension and Tristan da Cunha)` to `countries.json`.

ISO 3166 lists 249 countries - the `countries.json` is just missing two records.

We can keep the division json files in `data` in case anyone is interested in a specific part of a country (or for legacy reasons).

**Comment by mledoze** [comment]
Now that we have the `independent` flag, it makes sense to move the files `data/bes.divisions.json` and `data/shn.divisions.json` back into the main `countries.json` file. We'll also remove the *.divisions.json files because they are not useful anymore.

We'll fix the issue #254 in the same time.

Do you think you could do that?

**Comment by blumk** [comment]
Yes, I was waiting for the major PRs to be completed first. It might take me a week to submit a PR for both issues.

**Comment by mledoze** [comment]
Ok. Do you prefer me to fix these issues?

I'll merge the PR regarding the arabic translations this week.

**Comment by blumk** [comment]
@mledoze You decide. I'm quite busy at work but willing to fix them if you need help. As soon as the arabic translations are in master it would be a good time for a merge.

I think the records have to be updated with the latest changes in countries.json (emoji support, languages and so on).

**Comment by mledoze** [comment]
> I'm quite busy at work

Same here :)

I propose you fix these issues while I handle the merge of one of the two pull requests for arabic translations (there are still some problems with them).

> I think the records have to be updated with the latest changes in countries.json (emoji support, languages and so on).

Of course, you work will not be lost!

By the way, thank you very much for your help on this project, it's much appreciated.

**Comment by blumk** [comment]
@mledoze Thanks for maintaining this project! I'll provide a fix for the two issues.
