### ISSUE TITLE
Differences in names from ISO-3166

### ISSUE THREAD

**Issue by courtney-miles** [mledoze/countries#283]
Is the name of each county listed in `countries.json:[*].name.common` expected to the same as the **English Short Name** reported for the ISO 3166 standard at https://www.iso.org/obp/ui/

If it is, I'm happy to submit a PR to consolidate.

I won't type them all out, but the following are a few differences.

ISO 3166 English Short Name | `countries.json:[*].name.common`
---|---
French Southern Territories (the) | French Southern and Antarctic Lands
Bolivia (Plurinational State of) | Bolivia
Cabo Verde | Cape Verde
Korea (Republic of) | South Korea
Holy See | Vatican City

I see the ISO 3166 name for these countries in other keys, but there does not appear to be a consistent way to get this name.

**Comment by mledoze** [comment]
Hello @courtney-miles, the name listed in the `countries.json:[*].name.common` properties is not expected to be the same as in the ISO 3166 standard because I prefer "South Korea" instead of "Korea (Republic of)".

Thank you for your issue though.

**Comment by courtney-miles** [comment]
I understand.

My motivation for this was to head off complaints from clients who feel we have not chosen the right country name (because it happens.)  By adopting the ISO standard it removes "personal preference" from the argument.

But at the time I think had become too focused on standards and I can appreciate the current `common` name is more sensible for end users, and should be able to make do without the ISO country name.
