### ISSUE TITLE
Swaziland is now Eswatini

### ISSUE THREAD

**Issue by ndawg** [mledoze/countries#289]
The UN has officially recognized Swaziland's change to the name of Eswatini. How will this change be handled?

**Comment by blumk** [comment]
As soon as ISO updates the ISO 3166 standard, we'll update the entry.

See https://www.iso.org/obp/ui/#iso:code:3166:SZ

I recommend closing this issue and reopening a ticket again when the standard changes.

**Comment by mledoze** [comment]
@ndawg Could you please send me a pull request with the required changes to rename Swaziland to Eswatini please?
