### ISSUE TITLE
Custom `filter` query in API endpoint

### ISSUE THREAD

**Issue by atefBB** [mledoze/countries#291]
According to docs : `name` value `may` contains `comman`, `official` ... `sub-items`.
The API docs lack `custom filtering` requests like `name:common` or `name:official` (for example).
Is this `feature` exists or not?!
If it exists, how the API endpoint would look like?!

**Comment by mledoze** [comment]
Hello @atefBB, I think you posted this issue on the wrong project, because there is no API here. 

I think the right project is https://github.com/apilayer/restcountries
