### ISSUE TITLE
German translations inaccurate

### ISSUE THREAD

**Issue by robindaumann** [mledoze/countries#304]
I am using the JSON Version and found two inaccuracies in the German translations.

For South Africa, both the common and the official Names are "Republik Südafrika" where the common name should omit the "Republik" prefix as it is for the other countries.

For Moldova, the common translation is "Moldawie" but should be "Moldawien" like described here [wiki](https://de.wikipedia.org/wiki/Republik_Moldau).

**Comment by robindaumann** [comment]
I reviewed the issue and noticed that the described issues only occur in the dist/countries.json. Not in the top level countries.json

**Comment by robindaumann** [comment]
I ran the php script and the bugs do not occur in the dist folder anymore.

**Comment by mledoze** [comment]
Fixed by #305.
