### ISSUE TITLE
Feature: i18n currencies name

### ISSUE THREAD

**Issue by blacksmoke26** [mledoze/countries#307]
Saperate JSON file `currencies-i18n.json` which will store currencies name in various languages.

For example:
```
[
....
"URD" : {
  "AUD": "آسٹریلوی ڈالر",
  "PKR": "پاکستانی روپیہ",
  "USD": "امریکی ڈالر",
    ....
},
....
]
```

Is it worthy?

**Comment by mledoze** [comment]
Thank you for this idea @blacksmoke26 but I don't think it's worth it.

**Comment by blacksmoke26** [comment]
Ah! No issue!
