### ISSUE TITLE
No "native" should be {} instead of [].

### ISSUE THREAD

**Issue by fhuonder** [mledoze/countries#309]
The native element looks like :
```
"native": {
        "eng": {
          "official": "Cook Islands",
          "common": "Cook Islands"
        },
...
```

In case a country has no native it currently looks like:
```
{
    "name": {
      "common": "Antarctica",
      "official": "Antarctica",
      "native": []
    },
```

But I think the "no native" should look like:
```
{
    "name": {
      "common": "Antarctica",
      "official": "Antarctica",
      "native": {}
    },
```
The native isn't a list but a map. And an empty map is `{}`.

**Comment by mledoze** [comment]
Hello @fhuonder you're right, I'll fix this!

**Comment by mledoze** [comment]
It is fixed on master. I will publish a new release soon.

**Comment by fhuonder** [comment]
Do you already have a date when the new release is published?

**Comment by mledoze** [comment]
@fhuonder I will publish a new release today.

**Comment by mledoze** [comment]
@fhuonder here it is: https://github.com/mledoze/countries/releases/tag/v2.1.0
Sorry for the delay.

**Comment by fhuonder** [comment]
Thanks a lot 😊.
