### ISSUE TITLE
Flag descriptions

### ISSUE THREAD

**Issue by JmpEsc** [mledoze/countries#317]
I'm currently working on a flag identifier React app to search for flags by description. Would you be interested in a PR for the flag descriptions? Currently my descriptions looks like this:
`{"BR" : "brazil green yellow blue white rectangle circle device words stars ordem e progresso"`

I'm working on getting it more to something closer to:
```
"BR" : {
    "description" : {
        "colors" : "green yellow blue white",
        "shapes" : "rectangle quadrilateral circle",
        "device" : "disc banner stars",
        "words" : "ordem e progresso",
        "ratio" : "3:4",  
        "ciaFlagDescription" : "green with a large yellow diamond in the center bearing a blue celestial globe with 27 white five-pointed stars; the globe has a white equatorial band with the motto ORDEM E PROGRESSO (Order and Progress); the current flag was inspired by...",
        },  
 }
```

The CIA World Factbook is the only place I've found so far with easily parseable data. In lieu of using their descriptions, I may use openCV or try to munge the data from SVGs.
Anyway, please let me know if you'd even be interested in this. And thanks for this cool project, by the way.

**Comment by JmpEsc** [comment]
The CIA World Factbook is the only place I've found so far with easily parseable data. In lieu of using their descriptions, I may use openCV or try to munge the data from SVGs.
Anyway, please let me know if you'd even be interested in this. And thanks for this cool project, by the way.

**Comment by mledoze** [comment]
Hello @JmpEsc, IMO this kind of data is out of scope for this project. Thank for your offer though, I really appreciate it!
