### ISSUE TITLE
Missing columns in CSV file

### ISSUE THREAD

**Issue by lpellegr** [mledoze/countries#327]
Since your last update, at least the CSV content includes broken entries:

https://github.com/mledoze/countries/blob/e7c00bcb7a291a57970a338dd108e52fb0cee489/dist/countries.csv

For instance, row 29 should actually have 22 columns, instead of 21.

I noticed this regression since we have a parser that relies on your great data and parses the last column.

**Comment by mledoze** [comment]
Hello, thank you for this issue, I am sorry for the inconvenience, I will fix this right away.

**Comment by mledoze** [comment]
This has been fixed by #328 and merged on master.

Thank you for your patience.

**Comment by lpellegr** [comment]
@mledoze Thanks a lot for your responsiveness.
