### ISSUE TITLE
currency denominations

### ISSUE THREAD

**Issue by pjadanowski** [mledoze/countries#336]
it would be great to add currency denominations to each country currency object eg for Germany

Euro banknotes are issued in €500, €200, €100, €50, €20, €10, €5 notes. 
Denominations of Euro coins are €2, €1, 50c, 20c, 10c, 5c, 2c, and 1c.

**Comment by mledoze** [comment]
Hello @pjadanowski, 
thank you for your proposal, but I am afraid that currency denominations are too specific for this project. It is meant to be a general purpose dataset about countries.
