### ISSUE TITLE
No Chinese labels for countries

### ISSUE THREAD

**Issue by avarapayeva** [mledoze/countries#338]
Hello Colleagues, could you add Chinese translations support for list of countries?
[Countries.Chinese.zip](https://github.com/mledoze/countries/files/3334756/Countries.Chinese.zip)
We've prepared json with Chinese values for you. Could you please add them to the library?
It's a blocker for us to proceed with your solution.

Thank you in advance.

**Comment by MenosGrante** [comment]
Hey, I guess you can fork it and add your localization. I guess ODC licenses allows it until you will keep your fork open source.

Correct me, if I am wrong about licenses.

**Comment by mledoze** [comment]
Hello, the Chinese translations are already available in this project, it's in `translations.zho`.
