### ISSUE TITLE
South Sudan is empty, but Sudan has it included

### ISSUE THREAD

**Issue by calmforce** [mledoze/countries#349]
There are problems with both South Sudan country map and Sudan country map. The South Sudan map is empty: https://github.com/mledoze/countries/blob/master/data/ssd.geo.json

The Sudan country map is not empty, but it includes South Sudan, which is obviously wrong as well: https://github.com/mledoze/countries/blob/master/data/sdn.geo.json

What can be done about this? Are there known editors that I can use to edit Sudan GEO JSON file to make South Sudan out of it?

**Comment by mledoze** [comment]
Hello, thank you for reporting this issue.

> What can be done about this?
You are right, something is wrong. The source for the countries map is http://www.naturalearthdata.com/

I used QGIS to convert the shape files into GeoJSON.

Maybe you could update the maps of Sudan and South Sudan from the files of natural earth data using QGIS or other suitable tools?

**Comment by mledoze** [comment]
👋 Hello @calmforce, friendly ping ;)
