### ISSUE TITLE
Add two-letter ISO 639-1 language code

### ISSUE THREAD

**Issue by bbsnly** [mledoze/countries#359]
It would be nice to have the ISO 639-1 language code, when exists, for each language.

For example:
```json
{
  "country": "Italy",
  "languages": [{
    "ISO 639-3": "ita",
    "ISO 639-1": "it"
  }]
}
```

**Comment by mledoze** [comment]
Hello @bbsnly, thank you for your proposal. This project tries to provide only high-level data about countries and avoid too much detailed information. I would prefer that we stick to the three-letter language codes.
