### ISSUE TITLE
Outdated npm

### ISSUE THREAD

**Issue by Booster2ooo** [mledoze/countries#360]
Hello,

I noticed the npm package is outdated.
Would it be possible to update it?
Thanks a lot, keep on the good work!

Best regards,
Booster2ooo

**Comment by mledoze** [comment]
:wave: You are right, I will prepare a new release.

**Comment by mledoze** [comment]
Here is the release 3.0.0 

https://github.com/mledoze/countries/releases/tag/v3.0.0

**Comment by koesper** [comment]
4.1.0 also seems to be missing from NPM?
