### ISSUE TITLE
Adding commonly used abbreviations, such as "UK" for United Kingdom and "DE" for Germany

### ISSUE THREAD

**Issue by spekulatius** [mledoze/countries#363]
I know some information is in the alternative names, but it would be easier to have a clearly identifiable field for this. Otherwise, the title says it pretty much all.

**Comment by mledoze** [comment]
Hello, thank you for your proposal. I suggest you use the `cca2` property which resembles what you are looking for, although it's `GB` for United Kingdom.

Adding a field with commonly used abbreviations would be redundant with the `cca2` property.
