### ISSUE TITLE
Hebrew translation missed

### ISSUE THREAD

**Issue by xcarpentier** [mledoze/countries#372]

**Comment by mledoze** [comment]
Hello,
I managed to fetch the common countries name in Hebrew from Wikipedia, but I can't find a way to retrieve the official names. I tried to parse the text of each country page with no success. The fact that Hebrew is a right-to-left language, does not help.

Can someone help me on this?

Thank you

**Comment by xcarpentier** [comment]
Hi,
Any help @shem8 ?

**Comment by mledoze** [comment]
I am going to close this for now until someone figures out how to extract the Hebrew translations from Wikipedia.

**Comment by alonroth** [comment]
@mledoze Can I offer my help with the official names?
