### ISSUE TITLE
How to make sense of dialing code out of "idd" property?

### ISSUE THREAD

**Issue by VictorQueiroz** [mledoze/countries#378]
In a previous version we had `callingCode` property but now this property is gone. `idd` is rather confusing to me.

For example: Brazil country code is `55` but it is now split into `idd.root = 5` and then `idd.suffixes = [5]`. It doesn't make any sense to me.

Can someone explain to me how can I achieve original country code using this data?

**Comment by mledoze** [comment]
Hello @VictorQueiroz, 

it's rather simple: to construct the list of calling codes for a country, you need to concatenate the root part with each suffixes. 

The reasoning behind the refactoring of the old `callingCode` property can be found in the [original pull request](https://github.com/mledoze/countries/pull/124).

**Comment by mledoze** [comment]
This gave me an idea: we could recreate the old `callingCode` property at build time from the `idd` field, what do you think @VictorQueiroz?

**Comment by VictorQueiroz** [comment]
> This gave me an idea: we could recreate the old `callingCode` property at build time from the `idd` field, what do you think @VictorQueiroz?

Hi @mledoze,

sorry about the delay. I appreciate your initiative and attention with my issue. I think it'd be great to have that as a package that would use `world-countries` package underneath it. Seems less aggressive. :)

**Comment by mledoze** [comment]
There is no need for another package. I can generate the calling codes only in the [`dist`](https://github.com/mledoze/countries/tree/996bbcc84098b593d5e246990b522edf305bdc41/dist) files which are generated from the data in the main [`countries.json`](https://github.com/mledoze/countries/tree/996bbcc84098b593d5e246990b522edf305bdc41/countries.json).

**Comment by mledoze** [comment]
:wave: @VictorQueiroz it's done on master. I will release a new version by the end of this week.
