### ISSUE TITLE
Steps to make npm package smaller

### ISSUE THREAD

**Issue by kevinsimper** [mledoze/countries#386]
Right now the package is more than 100 kb

https://bundlephobia.com/result?p=world-countries@4.0.0

I would recommend we add a .npmignore so that for example .php files are not in the package.

**Comment by mledoze** [comment]
👋 You are right. I have been thinking about that too. I will take care of it.

**Comment by mledoze** [comment]
I prefer to use a whitelist instead of a blacklist. So I added the `files` property in `package.json` like so:

```
 "files": [
        "countries.json",
        "data/*",
        "dist/*",
        "index.d.ts",
        "index.js"
    ]
```

I am not sure this will save a lot since the `data` directory is big.

**Comment by kevinsimper** [comment]
@mledoze That is a even better idea! Thank you! 😄
