### ISSUE TITLE
Update common name of Czech Republic

### ISSUE THREAD

**Issue by kevinsimper** [mledoze/countries#387]
I was confused when I saw there was no Czech Repulic on the list, but then discovered it was Czechia, but I had never heard that before and have been multiple times to Czech Repulic.

I would argue that the common name should be changed to Czech Repulic

Here is also a article about the confusion:
https://www.theguardian.com/world/2016/oct/25/nobody-calls-it-czechia-czech-republic-new-fails-catch-on

**Comment by kevinsimper** [comment]
Okay, it should not be changed, I researched some more and it is just my ignorance, here it is prominent on Google Maps

![image](https://user-images.githubusercontent.com/1126497/78889158-6e5a8b00-7a63-11ea-999b-ace2cccd938f.png)

**Comment by mledoze** [comment]
To add to the confusion, Wikipedia page of the country is "Czech Republic", see the request to change the name to Czechia https://en.wikipedia.org/wiki/Talk:Czech_Republic#Move_request:_Move_Czech_Republic_to_Czechia

**Comment by kevinsimper** [comment]
@mledoze Haha that is really confusing 😅
