### ISSUE TITLE
Convert json file to module in npm package

### ISSUE THREAD

**Issue by kevinsimper** [mledoze/countries#390]
With ES6 modules it is not possible to load JSON files with using experimental JSON support.

https://nodejs.org/api/esm.html#esm_experimental_json_modules

I would suggest that the JSON file is converted to a js file and added `export default ` in front, which makes it a valid .js file.

This would also allow it to be loaded through Pika CDN, unpkg and sites alike, since the browser don't support loading JSON files either into JS without `JSON.parse`

https://www.pika.dev/search?q=world-countries

**Comment by mledoze** [comment]
Hello, I am not a JS developer, but should we modify the [`index.js`](https://github.com/mledoze/countries/blob/da8b09712f7319b5406eac4c37bfdbd68c4834f7/index.js) file instead?

**Comment by mledoze** [comment]
I close this fow now. Feel free to reopen it or send me a PR with the changes when you are ready.
