### ISSUE TITLE
Searching by language code - Tagalog (Filipino) TL doesn't exist

### ISSUE THREAD

**Issue by Arniox** [mledoze/countries#394]
I'm creating an auto-translation feature for website that takes input and automatically translates it with a tag for countries that use that language and so on.
I'm using google translate api to send text in, detect the language and then give me the resultant translated text with the resultant country code.

During testing, I noticed some languages/language codes spat out by google translate that was not supported by your database.
Namely, TL (Tagalog from the Philipinnes). (list of all the languages currently supported by google translate is here: https://cloud.google.com/translate/docs/languages)

Can you please add this language code to your database and also update any other missing languages?

**Comment by mledoze** [comment]
Hello, 
this dataset contains only the list of **official** languages. As per [Wikipedia](https://en.wikipedia.org/wiki/Philippines), Tagalog is not an official language, but a recognized regional language.
