### ISSUE TITLE
Errors in file countries-unescaped.json

### ISSUE THREAD

**Issue by DAP-GitHub** [mledoze/countries#399]
Probably due to errors in source files, to be taken into account when uploading them :
1. Kosovo has no attribute "independent" : suggestion, make it false by default
2. Antartica has "callingCodes":[] : suggestion, as we expect a string inside the array (such as "+49"), make it callingCodes":[""], as it is for «Heard Island and McDonald Islands»

**Comment by mledoze** [comment]
Hello @DAP-GitHub,



> Kosovo has no attribute "independent" : suggestion, make it false by default

The attribute `independent` is present for Kosovo, its value is `null`: https://github.com/mledoze/countries/blob/cc6993ec4e336d22232e64c63853793eba37b1cd/dist/countries-unescaped.json#L125
The reason for this value can be found here: https://github.com/mledoze/countries/pull/257#issuecomment-356522371

> Antartica has "callingCodes":[] : suggestion, as we expect a string inside the array (such as "+49"), make it callingCodes":[""], as it is for «Heard Island and McDonald Islands»

Antarctica has no official calling code, so the value `"callingCodes":[]` is correct. It's an error for «Heard Island and McDonald Islands», I will fix it.
