### ISSUE TITLE
Please remove “Province of China” from Taiwan

### ISSUE THREAD

**Issue by zhusee2** [mledoze/countries#4]
Hi mledoze,

Thanks for this great work, really handy and useful. However it would be even nicer if you can leave Taiwan alone, without the “, Province of China” appendix.

Well it's entirely understandable that this label comes from the ISO 3166 list, but the current truth is Taiwan has its own government and elected president, own currency and own passport. So it would be really thankful if you can just call it “Taiwan” instead. ;)

Thanks anyway,
Zhusee

**Comment by benpptung** [comment]
Hi, while checking the list for my project, I still see some inappropriates on the followings

https://github.com/mledoze/countries/blob/master/countries.json#L11177
`\u4e2d\u534e\u6c11\u56fd` should be corrected as `\u4e2d\u83ef\u6c11\u570b`

https://github.com/mledoze/countries/blob/master/countries.json#L11190
`Taiwan, Province of China` should be corrected as `Taiwan` or removed if it is duplicated.

https://github.com/mledoze/countries/blob/master/countries.json#L11201
`\u53f0\u6e7e\uff08\u53f0\u6e7e\u7701/\u4e2d\u83ef\u6c11\u56fd\uff09` would be better to be shorten to `\u53f0\u6e7e` . 

Thank you for your time :)

**Comment by herrjemand** [comment]
Good job @benpptung!

**Comment by herrjemand** [comment]
Could make a pull btw?

**Comment by mledoze** [comment]
Thank you @benpptung for your comment! I'd love a pull requests with these changes :)

**Comment by mledoze** [comment]
@benpptung PR #235 has been merged. Thank you for your help!

**Comment by nobodxbodon** [comment]
@mledoze seems https://github.com/Shopify/active_utils/pull/10 was closed because 
>"Taiwan, Province of China" is the ISO name

Should this PR be reverted, given that this project is based on the same ISO 3166?

**Comment by zhusee2** [comment]
I would be against reverting this PR.

Most citizens from Taiwan disagree the ISO name. For us we no longer see us as any part of China, which now represents the PRC. The ISO has been refusing to change this name because, you know, “China issues.”

I see this repository now refers Taiwan as “Republic of China (Taiwan)” and I'm very grateful for that. That's the name our own government is using to refer ourselves.

It'll be really kind if you can leave this list as it is for Taiwan, so we can have a chance to be called with our own name.

**Comment by nobodxbodon** [comment]
As the project README states, the data is "defined by ISO Standard 3166-1".

If it subjects to different personal opinions instead, it will hurt its credibility.

**Comment by Domon** [comment]
> As the project README states, the data is "defined by ISO Standard 3166-1".
> 
> If it subjects to different personal opinions instead, it will hurt its credibility.

It's not a personal opinion. The decision was practical and reflected the reality.

**Comment by jdh8** [comment]
The ISO 3166-1 is just an excuse of their political campaign to spread Chinese censorship over open-source projects.
https://github.com/nobodxbodon/one-China

**Comment by nobodxbodon** [comment]
No matter what my or your group's opinion is, the project states clearly that it's based on ISO 3166, and it should keep consistent with it as much as possible.

Otherwise this will just become a contest to see who's louder by comparing which side has more supporters, which I've been trying to avoid from the beginning.

**Comment by Lin-Buo-Ren** [comment]
@nobodxbodon 
> the project states clearly that it's based on ISO 3166, and it should keep consistent with it as much as possible.

I've proposed a fix for your concern, please review.

**Comment by mledoze** [comment]
Hello all, 

I will not revert this change that was made more than 6 years ago (https://github.com/mledoze/countries/commit/5403385561766789c44673ff1adb44552d93c050). Many projects use this dataset and are perfectly fine with the name of Taiwan.

> The ISO 3166-1 is just an excuse of their political campaign to spread Chinese opinion over open-source projects.
> https://github.com/nobodxbodon/one-China

Thank you for pointing that out. I will not be subject to Chinese propaganda.

Consider this topic closed.
