### ISSUE TITLE
Add the country states/regions

### ISSUE THREAD

**Issue by mledoze** [mledoze/countries#40]
The idea is to add the country states or regions (depending on the country). 

A format was proposed here: https://github.com/mledoze/countries/issues/6#issuecomment-27620009

@shanti2530 suggets to import the data from: http://vikku.info/programming/geodata/geonames-get-country-state-city-hierarchy.htm

I propose not to add cities because it would make the dataset too big in my opinion. I prefer to focus on top-level data.

**Comment by shehi** [comment]
So how can we wrap-up this proposal and get on working? :)

**Comment by mledoze** [comment]
@wiredmax any updates on this one? If you don't have time to finish this, it's not a problem, someone can take over.

**Comment by wiredmax** [comment]
@msabeh and I will start working on this. Starting today, we will fork it and structure the data this way if you still agree:

The only only change with the previously disccussed in this issue is the lower case type.

`/data/can.json5`
```
{
  name: "Quebec"
  nativeName: "Québec"
  type: "province"
  divisions: [
      { type: "region", name: 'Bas-Saint-Laurent' },
      { type: "region", name: 'Saguenay–Lac-Saint-Jean' },
      { type: "region", name: 'Capitale-Nationale' },
      { type: "region", name: 'Mauricie' },
      { type: "region", name: 'Estrie' },
      { type: "region", name: 'Montréal' },
      { type: "region", name: 'Outaouais' },
      { type: "region", name: 'Abitibi-Témiscamingue' },
      { type: "region", name: 'Côte-Nord' },
      { type: "region", name: 'Nord-du-Québec' },
      { type: "region", name: 'Gaspésie–Îles-de-la-Madeleine' },
      { type: "region", name: 'Chaudière-Appalaches' },
      { type: "region", name: 'Laval' },
      { type: "region", name: 'Lanaudière' },
      { type: "region", name: 'Laurentides' },
      { type: "region", name: 'Montérégie' },
      { type: "region", name: 'Centre-du-Québec' }
  ]
},
{
  name: "Ontario",
...
```

We'll start with the easy ones (from our perspective) North America and Europe, than South and Central America, Africa (starting with Magreb and Northern africa) then moving to Middle-East and Asia and then finish with all the special cases.

**Comment by mledoze** [comment]
@wiredmax I'm glad to hear that you are working on this. I still agree with the format. I think that we should use the same format for the `name` property. So in this case: 

```json
"name": {
	"common": "Quebec",
	"native": {
		"fra": {
			"common": "Québec"
		}
	}
}
```
It's a bit verbose, but it's coherent with the data in [`countries.json`](/mledoze/countries/blob/master/countries.json).

What do you think?

**Comment by mathieumg** [comment]
@wiredmax I imagine you meant to use double-quotes for the names?

@mledoze I agree, while it's more verbose it's more thorough, more flexible and (as you pointed out) consistent with the rest.

**Comment by wiredmax** [comment]
@mathieumg Yes they are double quoted since it's regluar JSON and not JSON5

**Comment by wiredmax** [comment]
@mledoze For the name I agree to, but shall we do it only at the first level or both? Doing it on both level seems a bit heavy for me since to me the native name is the one always used. 

```
{
  "name": {
    "common": "Alberta",
    "native": {
      "eng": {
            "common": "Alberta"
    }
  },
  "type": "province"
  "divisions": [
      { "type": "district", "name": 'Acadia' },
      { "type": "district", "name": 'Athabasca' },
...
```
vs

```
{
  "name": {
    "common": "Alberta",
    "native": {
      "eng": {
            "common": "Alberta"
    }
  },
  "type": "province"
  "divisions": [
      { 
         "type": "district",
          "name": {
             "common": "Acadia",
             "native": {
               "eng": "Acadia"
             }
           }
       },
      { 
         "type": "district",
          "name": {
             "common": "Athabasca",
             "native": {
               "eng": "Athabasca"
             }
           }
       },
...
```

**Comment by mledoze** [comment]
@wiredmax yes doint it on both levels is too heavy. 

This solution
```json
{
  "name": {
    "common": "Alberta",
    "native": {
      "eng": {
            "common": "Alberta"
    }
  },
  "type": "province",
  "divisions": [
      { "type": "district", "name": "Acadia" },
      { "type": "district", "name": "Athabasca" },
```
is better :+1:

**Comment by mathieumg** [comment]
> Yes they are double quoted since it's reglular JSON and not JSON5.

But you keep using single quotes in your examples. :wink:

**Comment by wiredmax** [comment]
All good then @msabeh will start working on the fork, starting with North America, once done I'll submit a PR that we could merge in a regions branch onto your project and see if there's needed ajustements and then continue further with Europe.  Once all the regions of the word are 98% (2% we are talking about the weird case we will probably find) you could then merge onto master.

@mathieumg I know, I didn't notice them, I've fixed it in my last comment, no worries. Anyway @mabeh atom will notice her of single quotes.

**Comment by msabeh** [comment]
Yay! I'll be working on this this afternoon, I'll keep you guys posted.

**Comment by justqyx** [comment]
Hi all, thanks for the job all of you've been done. I'd like to ask there is a considerable progress about this issue?

**Comment by mledoze** [comment]
@justqyx hello, unfortunately I think this PR is dead, would you like to work on it?

**Comment by mledoze** [comment]
I'll close this issue for the moment. If someone want to work on it, feel free to open a new issue.

**Comment by adrienne** [comment]
Bookmarking this as a reminder to myself because i might be able to help.

**Comment by mledoze** [comment]
@adrienne your help is welcome! :slightly_smiling_face:
