### ISSUE TITLE
Simple API to download country files

### ISSUE THREAD

**Issue by DAP-GitHub** [mledoze/countries#400]
Hello,
Unless it already exists (but I have not found it),
It would be useful to have a simple API to dowload the files such as
https://github.com/mledoze/countries/download/countries-unescaped.json. This HTTP request could easiliy be integrated in any program to fetch/update the list.
Thanks

**Comment by mledoze** [comment]
Hello, 
you should check this project https://github.com/apilayer/restcountries whose data comes from my project.

If you need to access the files from this project directly, you can always access them via `raw.githubusercontent.com`: https://raw.githubusercontent.com/mledoze/countries/master/dist/countries-unescaped.json
