### ISSUE TITLE
Wrong svg file for cuba country

### ISSUE THREAD

**Issue by hexabyte23** [mledoze/countries#405]
data/cub.svg is bad formated

**Comment by mledoze** [comment]
Thank you, I'll look into it.

**Comment by BordyV** [comment]
Hi are you still looking into it ? 😄

**Comment by hexabyte23** [comment]
yes sure

**Comment by mledoze** [comment]
> Hi are you still looking into it ? 😄

Oups sorry for the delay. I got caught up by life... I will fix it today.

**Comment by mledoze** [comment]
It's fixed on master.

https://github.com/mledoze/countries/blob/133ab7e80e8b175b6b828d0e93f21cfc6cbb7cce/data/cub.svg
