### ISSUE TITLE
Geojson Omissions

### ISSUE THREAD

**Issue by jamespwilliams** [mledoze/countries#407]
There are a few omissions in the geojson (and presumably topojson) of this repo:

- The Dutch part of Sint Maarten is labeled with ISO_A2 BL, when it should be SX
- BQ (https://en.wikipedia.org/wiki/Caribbean_Netherlands) is missing
- CW (https://en.wikipedia.org/wiki/Cura%C3%A7ao) is missing

I'll have a go at fixing these this morning.

Once these are fixed, this repo will have geojson/topojson for all ISO_A2 country codes.

**Comment by mledoze** [comment]
Hello @jamespwilliams, thank your for your help. FYI the GeoJSON data comes from http://www.naturalearthdata.com/

**Comment by jamespwilliams** [comment]
Couple more issues I've noticed as I'm working on this:

- BL (St Bartholemy) needs to have its *json corrected, since this data currently says it is where SX is
- GP includes St Bartholemy when it shouldn't

My plan to fix is to remove BL from GP, and then add BL's actual location.
