### ISSUE TITLE
Central Europe wrong?

### ISSUE THREAD

**Issue by tinohager** [mledoze/countries#410]
During my last data comparison I noticed that there is only one country with the following region "Central Europe"

https://github.com/mledoze/countries/search?q=%22Central+Europe%22

**Comment by tinohager** [comment]
The SubRegion is here `Eastern Europe`

https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/SK.yaml

**Comment by mledoze** [comment]
You are right, I will fix this.
