### ISSUE TITLE
[feature] Country time zone 

### ISSUE THREAD

**Issue by egyleader** [mledoze/countries#412]
is there any current way to get get countries time zone `ex:UTC+2` from this package ??
 and if not should I add a pull request by this data ?

**Comment by mledoze** [comment]
Hello, unfortunately this repository does not contain timezone data, only static data. This is choice that I made a long time ago, see [`CONTRIBUTING.md`](https://github.com/mledoze/countries/blob/133ab7e80e8b175b6b828d0e93f21cfc6cbb7cce/CONTRIBUTING.md).

However you can find timezone data in an other project that use this dataset, see: https://gitlab.com/amatos/rest-countries

**Comment by egyleader** [comment]
thanks for clarification
