### ISSUE TITLE
Wrong German translation of Hong Kong in Webservice

### ISSUE THREAD

**Issue by tloebhard** [mledoze/countries#416]
Hi,

https://restcountries.com/v2/name/Hong%20Kong
https://restcountries.eu/rest/v2/name/Hong%20Kong
deliver `"de": "Hong Kong",` (which is wrong)

In https://github.com/mledoze/countries/blob/master/countries.json it is correct: (https://de.wikipedia.org/wiki/Hongkong)
```
            "deu": {
                "official": "Sonderverwaltungszone Hongkong der Volksrepublik China",
                "common": "Hongkong"
            },
```

In https://github.com/apilayer/restcountries/blob/master/src/main/resources/countriesV2.json (no more maintained?) there is this error, too, but I can't find the corresponding file here.

Maybe here needs something to be regenerated?

Thank you!

**Comment by mledoze** [comment]
Hello,

this dataset is not directly used by the restcountries.com API. The project https://github.com/apilayer/restcountries/ appears to be no longer maintained. You should open an issue on this fork https://gitlab.com/amatos/rest-countries instead.
