### ISSUE TITLE
Incorrect flags urls for Ukraine

### ISSUE THREAD

**Issue by mikhov-ivan** [mledoze/countries#436]
**Steps to reproduce:**
1. Do a GET request: https://restcountries.com/v3/name/ukraine
2. Check "flags" field in the response.

**Actual result:**
Flags of Uganda are returned for the Ukraine.
https://restcountries.com/data/uga.*

**Expected result:**
Flags of Ukraine are returned in "flags".
https://restcountries.com/data/ukr.*

![bug](https://user-images.githubusercontent.com/39436815/134486440-2fc244dd-25ab-4af0-81b8-2f9f53c9f2c6.png)

**Comment by Dhia52** [comment]
I noticed this issue too. Here is a more readable screenshot of the response.

![image](https://user-images.githubusercontent.com/46674571/134819488-a9e62d3b-8662-4a87-988a-513bc94770ec.png)

**Comment by amatosg** [comment]
This project does not uses flags

**Comment by mledoze** [comment]
Hello, I think you've made a mistake. The repository for https://restcountries.com/ is here https://gitlab.com/amatos/rest-countries
