### ISSUE TITLE
cca2 in altSpellings

### ISSUE THREAD

**Issue by ePascalC** [mledoze/countries#437]
Hi @mledoze, what is the reason to have the cca2 also in altSpellings? Is that from history or it has a sense for e.g. searching?

**Comment by ePascalC** [comment]
@mledoze Just checking if you have any idea?

**Comment by mledoze** [comment]
Sorry for the delay.

Yes it was meant for searching, but I guess that it's not very useful now because a smart search program could easily find a country based on various fields: `name`, `cca2`, `cca3`, `altSpellings`, etc.

I guess we could remove the cca2 code from altSpellings.
