### ISSUE TITLE
Default order of countries

### ISSUE THREAD

**Issue by ebenh** [mledoze/countries#438]
Is there a reason why the default order of countries isn't alphabetical?

For instance, the list starts with "Aruba" instead of "Afghanistan".

IMHO, the list should be sorted by ISO 3166-1 alpha-2 code by default.

**Comment by mledoze** [comment]
The reason is that the countries are sorted by ISO 3166-1 alpha-3 code. The sort by ISO 3166-1 alpha-2 code puts Andorra first but not Afghanistan.
