### ISSUE TITLE
Chinese language-based countries do not include `zho` in `translations`

### ISSUE THREAD

**Issue by lanierc** [mledoze/countries#439]
## Expected behaviour

- Countries whose native language is Chinese should have `zho` appear in translations like other countries have their native languages appear within the `translations` array

## Actual behaviour

- Countries whose native language is Chinese omits `zho` from the `translations` array.

## Replicate

- Search for South Korea or North Korea in the API.
  - Notice that `kor` appears in the `translations` array, despite both countries' native language being Korean.
- Search for Taiwan, Hong Kong, Macau, or People's Republic of China in the API.
  - Notice that `zho` does not appear in the `translations` array. The last language, alphabetically, that appears in the array is `urd`.

**Comment by mledoze** [comment]
This has been fixed in #498
