### ISSUE TITLE
Wrong flag for Afghanistan

### ISSUE THREAD

**Issue by I-keep-trying** [mledoze/countries#440]
Taliban flag? Really??? smh...

The json data (v 3.1) currently has the following links for flag images: 

```
"flags":{
"png":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
"svg":"https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg"
}
```

I found the correct flag image, svg only, here: 
```
https://upload.wikimedia.org/wikipedia/commons/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg
```

or both formats here:
```
https://flagcdn.com/256x192/af.png //different sizes available
https://flagcdn.com/af.svg
```
I'm not from Afghanistan, so, if I'm wrong about this, please let me know, and accept my deepest apologies.

**Comment by jjlharrison** [comment]
I think you have this repository mixed up with another. There is no "v 3.1" of this project and the flag of Afghanistan is not the Taliban flag: https://github.com/mledoze/countries/blob/master/data/afg.svg

**Comment by I-keep-trying** [comment]
OMG so sorry, please accept my apologies. 

I was confused because the error is in https://restcountries.com/v3.1/all - restcountries.com identifies this repo (you) under "sources" among several others, and I guess I jumped the gun before I verified which source provided the wrong flag. 

Again, sorry!

**Comment by mledoze** [comment]
@I-keep-trying no worries. The project at restcountries.com was built with this dataset but, as far as I know, the data is not synchronized anymore.
