### ISSUE TITLE
If I use your project what license should I mention?

### ISSUE THREAD

**Issue by evshvarov** [mledoze/countries#442]
Hi!
Thanks for the great repo!
If I use the data from your project what license should I use?
1) the same [ODC ODbL](https://github.com/mledoze/countries/blob/master/LICENSE)?
2) no license included but mention your repo in the source?

What about the code in my project for which I wanted to use MIT License. Should I mention both?
Thanks in advance!

**Comment by mledoze** [comment]
Hi, AFAIK and according to the [ODbL license](https://en.wikipedia.org/wiki/Open_Database_License), you must use the same license. You can use the example notice provided in the license: https://github.com/mledoze/countries/blob/86fd7ef8076dd65e2527b95d67d03e0b09044f42/LICENSE#L271-L275

> What about the code in my project for which I wanted to use MIT License. Should I mention both?

You keep the MIT license for your project but you must add a notice regarding the data (and its license) from this repository. (Disclaimer: I am not a legal expert).
