### ISSUE TITLE
Kosovo cca3

### ISSUE THREAD

**Issue by schaumannj** [mledoze/countries#443]
Dear All,
do you think that the Kosovo country code in alpha 3 ISO can be changed to KOS from UNK?

**Comment by ePascalC** [comment]
To my knowledge Kosovo does not have an official 3-digit code yet, but I would stick to UNK.
For passports UNK is used (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3)

**Comment by mledoze** [comment]
I would stick with UNK for the moment. `KOS` is the IOC country code, see https://en.wikipedia.org/wiki/Country_codes:_J%E2%80%93K#_Kosovo
