### ISSUE TITLE
Singapore and Malaysia borders

### ISSUE THREAD

**Issue by schaumannj** [mledoze/countries#444]
Dear All,
do you think that Singapore and Malaysia can have the same borders if India and Sri Lanka has them?

**Comment by schaumannj** [comment]
moreover Sri Lanka has India as neighbor but India does not (India borders are only ['BGD', 'BTN', 'MMR', 'CHN', 'NPL', 'PAK'])

**Comment by mledoze** [comment]
No, the `borders` property contains only land borders, Singapore and Malaysia cannot have the same borders.
