### ISSUE TITLE
Bangladesh area is Wrong

### ISSUE THREAD

**Issue by NMRayhan** [mledoze/countries#448]
Hi,

Going to https://restcountries.com/v3.1/alpha/bd (Bangladesh), the area is wrong.
resource: https://en.wikipedia.org/wiki/Bangladesh

Actual result:
area: 147,570 km²

Expected result:
population: 148,460 km²

**Comment by xgebi** [comment]
RestCountries.com has data in different repository https://gitlab.com/amatos/rest-countries

**Comment by mledoze** [comment]
@xgebi is right, you should open an issue on https://gitlab.com/amatos/rest-countries repository.
