### ISSUE TITLE
Include the State of Palestine 🇵🇸

### ISSUE THREAD

**Issue by reeseovine** [mledoze/countries#452]
https://en.wikipedia.org/wiki/State_of_Palestine

You might notice there are areas bordering Israel, often referred to as the West Bank and Gaza Strip. These belong to Palestine which declared independence in 1988 and is recognized by 138 UN member states.

**Comment by herrjemand** [comment]
@reeseovine It does have it
<img width="137" alt="Screen Shot 2022-11-14 at 01 37 11" src="https://user-images.githubusercontent.com/1636116/201545788-c77a2034-8be4-44e1-9b71-c7f48963e96c.png">
