### ISSUE TITLE
Typo in dist/countries-unescaped.json 

### ISSUE THREAD

**Issue by Emil-Wozniak** [mledoze/countries#453]
In line line 81, in translations for "United Kingdom"

 "pol": { "common": "Zjednoczone Krłlestwo"  } should be "Zjednoczone Królestwo"
 
 Sample of use:
 https://pl.wikipedia.org/wiki/Zjednoczone_Kr%C3%B3lestwo
 https://ec.europa.eu/taxation_customs/ue-zjednoczone-krolestwo-nowe-stosunki_et

**Comment by mledoze** [comment]
fixed by #489
