### ISSUE TITLE
Flag/map licensing

### ISSUE THREAD

**Issue by hyandell** [mledoze/countries#454]
Hi Mohammed,

I'm unsure what the flag/map licensing is. ODBL is a bit unusual for, at least, images. 

I noticed in https://github.com/mledoze/countries/issues/340 that the flag came from https://github.com/apilayer/restcountries

That project appears to be under the MPL-2.0 license. Are the flags all under MPL-2.0? Is the map data also from there?

**Comment by mledoze** [comment]
This is a tricky subject, I'm not proficient in licensing. As far as I know all flags come from Wikipedia, so they should have the same license.

**Comment by hyandell** [comment]
Thanks - flags being more complicated than most ( https://en.wikipedia.org/wiki/Wikipedia:Copyright_on_emblems is a document on the subject; and as you dig deeper you find warnings like this "This image shows a [flag](https://en.wikipedia.org/wiki/flag), a [coat of arms](https://en.wikipedia.org/wiki/coat_of_arms), a [seal](https://en.wikipedia.org/wiki/seal_(device)) or some other official [insignia](https://en.wikipedia.org/wiki/insignia). The use of such symbols is restricted in many countries. These restrictions are independent of the [copyright](https://en.wikipedia.org/wiki/copyright) status."

My suggestion is to link back to Wikipedia here, both to https://en.wikipedia.org/wiki/Wikipedia:Copyright_on_emblems and to https://en.wikipedia.org/wiki/Gallery_of_sovereign_state_flags

(I know you say "The rest comes from Wikipedia" but I'll admit that wasn't something I picked up on and felt comfortable related to the flag images)

**Comment by mledoze** [comment]
> My suggestion is to link back to Wikipedia here, both to https://en.wikipedia.org/wiki/Wikipedia:Copyright_on_emblems and to https://en.wikipedia.org/wiki/Gallery_of_sovereign_state_flags

Thanks for the suggestion, I will add that to the readme.
