### ISSUE TITLE
inconsistent specification of the absence of calling codes

### ISSUE THREAD

**Issue by minisaw** [mledoze/countries#465]
the unescaped json generated file https://raw.githubusercontent.com/mledoze/countries/master/dist/countries-unescaped.json contains the "no calling codes" specification in several different manners, e.g.

Heard Island and McDonald Islands:
    "callingCodes": [
      ""
    ]

Antarctica:
    "callingCodes": []

i think it would be better to use a unified convention, e.g. the empty array only.

**Comment by mledoze** [comment]
Hi @minisaw, you're right, I will fix this.

**Comment by mledoze** [comment]
fixed via #488
