### ISSUE TITLE
timezone update

### ISSUE THREAD

**Issue by Deepanshusuman** [mledoze/countries#474]
timezone update from https://github.com/eggert/tz/blob/main/zone.tab

addition of 
```
MX	+3144-10629	America/Ciudad_Juarez	Chihuahua (US border - west)
```
and removal timezones from Canada 

```
America/Pangnirtung
America/Yellowknife
```

**Comment by mledoze** [comment]
Hello, 

This repository does not contain timezone data. 

If you are talking about https://restcountries.com/, please open an issue here https://gitlab.com/restcountries/restcountries/-/issues
