### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dakur** [mledoze/countries#479]
@mledoze Could you please release a new version with support for symfony/console@6 which is already in main branch?

**Comment by mledoze** [comment]
The 4.1.0 version is released https://www.npmjs.com/package/world-countries/v/4.1.0

**Comment by dakur** [comment]
It's strange, but according to [packagist](https://packagist.org/packages/mledoze/countries), v4.1.0 is already released from 2022-02-25, but still contains the old constraints:

![image](https://github.com/mledoze/countries/assets/9862581/61c7dc08-b6d0-4531-b178-cbd6a5a9e325)

**Comment by mledoze** [comment]
@dakur I think that I released the 4.1.0 version on Packagist last year but forgot to release it on npm.

**Comment by dakur** [comment]
@mledoze But the point is that the added constraint for [symfony/console ^6.0](https://github.com/mledoze/countries/blob/master/composer.json#L28) is not propagated to Packagist so there must be some version mismatch in this package..

**Comment by dakur** [comment]
Yep, great, that's what I meant. Looking forward to the release, thanks for taking care.
