### ISSUE TITLE
Error when yarn build

### ISSUE THREAD

**Issue by ngoc2003** [mledoze/countries#493]
I got this error when run `yarn buid`. I have tried [this](https://stackoverflow.com/questions/77100089/how-can-i-resolve-node-module-error-when-deploying-a-project-to-vercel) but it still not working! What should i do:((
<img width="563" alt="Screen Shot 2023-09-17 at 18 17 43" src="https://github.com/mledoze/countries/assets/90141097/f24089ce-befd-4498-a3ff-15d09fef9ba5">

**Comment by mledoze** [comment]
Hi, 

which version of the package do you use?

**Comment by mledoze** [comment]
Does this fix https://github.com/mledoze/countries/commit/3100acd7f5fdcf458ea3279800608ea96ddbb6d0 would help you?

**Comment by ngoc2003** [comment]
Hi @mledoze , I have fixed this error by changing version of package from 4.1.1 to 4.0.0

**Comment by mledoze** [comment]
Do you know why the 4.0.0 version works and not the 4.1.1?
