### ISSUE TITLE
Kosovo is missing

### ISSUE THREAD

**Issue by endrits079** [mledoze/countries#531]
Data for Kosovo are missing

**Comment by BusinessClick** [comment]
It seems to be `153` for `ISO 3166-1` Kosovo code.

Found on: https://www.rallybel.com/it/links_iso_code3.html

So this is the Json:
`{"name":{"common":"Kosovo","official":"Republic of Kosovo","native":{"sqi":{"official":"Republika e Kosov\u00ebs","common":"Kosova"},"srp":{"official":"\u0420\u0435\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u041a\u043e\u0441\u043e\u0432\u043e","common":"\u041a\u043e\u0441\u043e\u0432\u043e"}}},"tld":[".xk"],"cca2":"XK","ccn3":"153","cca3":"UNK","cioc":"KOS","independent":null,"status":"user-assigned","unMember":false,"currencies":{"EUR":{"name":"Euro","symbol":"\u20ac"}},"idd":{"root":"+3","suffixes":["83"]},"capital":["Pristina"],"altSpellings":["XK","\u0420\u0435\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u041a\u043e\u0441\u043e\u0432\u043e"],"region":"Europe","subregion":"Southeast Europe","languages":{"sqi":"Albanian","srp":"Serbian"},"translations":{"ces":{"official":"Kosovsk\u00e1 republika","common":"Kosovo"},"deu":{"official":"Republik Kosovo","common":"Kosovo"},"est":{"official":"Kosovo Vabariik","common":"Kosovo"},"fin":{"official":"Kosovon tasavalta","common":"Kosovo"},"fra":{"official":"R\u00e9publique du Kosovo","common":"Kosovo"},"hrv":{"official":"Republika Kosovo","common":"Kosovo"},"hun":{"official":"Koszov\u00f3","common":"Koszov\u00f3"},"ita":{"official":"Repubblica del Kosovo","common":"Kosovo"},"kor":{"official":"\ucf54\uc18c\ubcf4 \uacf5\ud654\uad6d","common":"\ucf54\uc18c\ubcf4"},"nld":{"official":"Republiek Kosovo","common":"Kosovo"},"per":{"official":"\u062c\u0645\u0647\u0648\u0631\u06cc \u06a9\u0648\u0632\u0648\u0648","common":"\u06a9\u0648\u0632\u0648\u0648"},"pol":{"official":"Republika Kosowa","common":"Kosowo"},"por":{"official":"Rep\u00fablica do Kosovo","common":"Kosovo"},"rus":{"official":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u041a\u043e\u0441\u043e\u0432\u043e","common":"\u0420\u0435\u0441\u043f\u0443\u0431\u043b\u0438\u043a\u0430 \u041a\u043e\u0441\u043e\u0432\u043e"},"slk":{"official":"Republika Kosovo","common":"Kosovo"},"spa":{"official":"Rep\u00fablica de Kosovo","common":"Kosovo"},"swe":{"official":"Republiken Kosovo","common":"Kosovo"},"urd":{"official":"\u062c\u0645\u06c1\u0648\u0631\u06cc\u06c1 \u06a9\u0648\u0633\u0648\u0648\u06c1","common":"\u06a9\u0648\u0633\u0648\u0648\u06c1"},"zho":{"official":"\u79d1\u7d22\u6c83\u5171\u548c\u56fd","common":"\u79d1\u7d22\u6c83"}},"latlng":[42.666667,21.166667],"landlocked":true,"borders":["ALB","MKD","MNE","SRB"],"area":10908,"flag":"\ud83c\uddfd\ud83c\uddf0","demonyms":{"eng":{"f":"Kosovar","m":"Kosovar"},"fra":{"f":"Kosovare","m":"Kosovar"}},"callingCodes":["+383"]}`

**Comment by mledoze** [comment]
Kosovo is already included in the dataset.
