### ISSUE TITLE
The data for Canada contains duplicates of 3 calling codes.

### ISSUE THREAD

**Issue by expeehaa** [mledoze/countries#543]
The calling codes for Canada contain the following 3 items multiple times:
* `"+1782"` (2 times)
* `"+1902"` (2 times)
* `"+1867"` (3 times)

I assume this is a mistake, as I don’t see any reason why any calling code would be duplicated in the same list.

**Comment by mledoze** [comment]
Hi,
thank you for your issue. It's a mistake, duplicate calling codes should not appear in the dataset. Do you mind sending a PR to fix this?
