### ISSUE TITLE
Bug!

### ISSUE THREAD

**Issue by wavewa** [mledoze/countries#547]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `world-countries@4.1.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/world-countries/index.d.ts b/node_modules/world-countries/index.d.ts
index aee9883..f265b65 100644
--- a/node_modules/world-countries/index.d.ts
+++ b/node_modules/world-countries/index.d.ts
@@ -42,7 +42,7 @@ export interface Country {
   languages: { [languageCode: string]: string }
   translations: { [languageCode: string]: OfficialAndCommon }
   latlng: [number, number]
-  demonyms: { [languageCode: string]?: Demonyms }
+  demonyms: { [languageCode: string]: Demonyms }
   landlocked: boolean
   borders: string[]
   area: number
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mledoze** [comment]
Hi, this was fixed by #483
