### ISSUE TITLE
What data to add next? 

### ISSUE THREAD

**Issue by mledoze** [mledoze/countries#6]
I would like to discuss here the data that should be added to this repository. 

A similar project like 0xJS [1] contains a lot more data such as the land area or the latitude/longitude coordinates of each country. 

Is it interesting/useful to have this kind of data too? 

Data that can be added:
- land (land mass in square kilometers [3])
- latitude (latitude coordinate of the capital [2])
- longitude (longitude coordinate of the capital [2])
- east (longitude of the country's eastern boundary [3])
- north (latitude of the country's northern boundary [3])
- south (latitude of the country's southern boundary [3])

What would you like to be added? 

Please let me know in the comments. 

[1] http://oxjs.org/#doc/Ox.COUNTRIES
[2] source: http://opengeocode.org/
[3] source: https://oxjs.org/#doc/Ox.COUNTRIES

---

**From the comments**
- add the type of the country (country, sovereign state, public body, territory, etc.)
- add the land borders (**done**, see https://github.com/mledoze/countries/tree/v1.3)
- add regions, provinces and cities

**Comment by herrniemand** [comment]
@mledoze I think we need to update translations objects according to the "name" object.
```json
"translations":{
	"de": {
		"common":"Russland",
		"official":"Russische Föderation"
	}...
}
```

**Comment by mledoze** [comment]
@herrniemand I'm ok with this change, although I'm reserved about the increased size of `countries.json`.

**Comment by Sjord** [comment]
I would like to know whether a country is in the [European Union]. Is that something suitable for this project to include for every country?

**Comment by mledoze** [comment]
@Sjord 

> I would like to know whether a country is in the European Union. Is that something suitable for this project to include for every country?

This has been asked here before (https://github.com/mledoze/countries/issues/6#issuecomment-46950625) and answered (https://github.com/mledoze/countries/issues/6#issuecomment-47659566). Unfortunately, this is not suitable to include in this project.

Though, thank you for asking!

**Comment by herrniemand** [comment]
@mledoze I kept translation in one line to keep it smaller.

**Comment by mledoze** [comment]
> I kept translation in one line to keep it smaller.

@herrniemand I saw it, very good.

**Comment by mledoze** [comment]
Yay :smile:  I just got this short URL http://git.io/countries for this project!

**Comment by petert82** [comment]
Sweet! :dancers:

**Comment by herrniemand** [comment]
@mledoze YAY!!!!!!!!!XD

**Comment by shehi** [comment]
I strongly would advise the addition of provinces and major cities.

**Comment by herrniemand** [comment]
@shehi #40 is the discussion about that. And @fayder proposed [here(comment)](https://github.com/mledoze/countries/issues/6#issuecomment-27620009) the structure.

**Comment by herrniemand** [comment]
@mledoze I just posted it on echojs... and it gone... XD
![tumblr_inline_nglo2t4jud1raprkq](https://cloud.githubusercontent.com/assets/1636116/6037427/67ec2f5e-acb8-11e4-9dd8-d74e431c0493.gif)

**Comment by mledoze** [comment]
@herrniemand yay thank you:) http://www.echojs.com/news/13325

**Comment by herrniemand** [comment]
@mledoze XD Thank you dude! Bloody brilliant idea! XD

**Comment by mledoze** [comment]
Yesterday was a good day, look at the stats: https://github.com/mledoze/countries/graphs/traffic

**Comment by herrniemand** [comment]
@mledoze its maintainers only view *( Send screenshot.

**Comment by mledoze** [comment]
![capture](https://cloud.githubusercontent.com/assets/576509/6038000/991d224a-ac59-11e4-95d7-c4560a08c029.PNG)

**Comment by herrniemand** [comment]
@mledoze Nice! *)

**Comment by qweek** [comment]
Add sea borders

**Comment by cumanacr** [comment]
Hi, super useful project! 
Thanks for maintaining it.

I'm aware that population data were added it, then, were removed on:

> @herrniemand population data was already added to this dataset (81fa9f6) but later removed (see #6 (comment)).

But, What about include population historical data only?

Like this:

```javascript
        "name": {
            "common": "Costa Rica",
            "official": "Republic of Costa Rica",
            "native": {
                "spa": {
                    "official": "Rep\u00fablica de Costa Rica",
                    "common": "Costa Rica"
                }
            }
        },
.
.
.
        "population": {
            "2013": { "unit": "million", "amount":"4.872" },
            "2012": { "unit": "million", "amount":"4.805" },
            "2011": { "unit": "million", "amount":"4.738" },
            "2010": { "unit": "million", "amount":"4.67" },
        }
 }
```
And we can get another interesting historical info for each country from [google](https://www.google.com/search?client=ubuntu&hs=ESQ&channel=fs&q=costa+rica+population&stick=H4sIAAAAAAAAAGOovnz8BQMDw2MOHiUO_Vx9A8MCi2ItrexkK_2c_OTEksz8PP3iEiBdXJKZnJgTX5SaDhSyKsgvKM0By3YxmnHBNQqRo9G0sMKQLI1G2RbZpGjs16o74nctpOFW9fnrLo2rxL55tOwGAKh4gTsAAQAA&sa=X&ei=TwPtVNrfB4SZNoGwg_AJ&ved=0CCEQth8wAA&biw=1920&bih=851) like:
* Life expectancy
* GDP per capita
* Fertility rate

Same pattern

```javascript
        "lifeExpectancy": {
            "2012": { "unit": "year", "amount":"79.7" },
            "2011": { "unit": "year", "amount":"79.49" },
            "2010": { "unit": "year", "amount":"79.28" },
        }
```

What do you think?
I would be glad to help with this

Regards

**Comment by mledoze** [comment]
Hello @cumanacr, thank you for your comment but unfortunately this project does not contains historical data. One good candidate for this kind of data would be the [tinata](https://github.com/tinata/tinata) project, you could ask there.

**Comment by cumanacr** [comment]
@mledoze thanks, but no thanks, I like this project :smiley: 

Maybe a separate file like #40 proposes for the country regions but on historical data, eg:
 
* cri.historicaldata.json
* cri.hdata.json
* cri.hd.json

This way, countries.json keeps small.

maybe something like that, is better?

Regards

**Comment by JacquesMarais** [comment]
Multiple Capitals.

**Comment by Purus** [comment]
We have just the list of languages. How about adding official languages? For example, India has too many languages and there are around 15+ official languges out of all.

**Comment by mledoze** [comment]
@Purus the `languages` property already contains the list of official languages for each country (see [README](https://github.com/mledoze/countries/blob/a0f1c99f7c7217a06b14871463dbc6e75dbdd603/README.md)). I know that there are some countries with many recognised regional languages, I would prefer no to take them into account as it would make the dataset too big.

**Comment by thefabulousdev** [comment]
How about adding the currencies names?

e.g. 
```js
    "currencies" : {
      "eur" : "Euro",
      "mxn" : "Peso"
    }
```

**Comment by petert82** [comment]
@thefabulousdev For me, that's something that's better solved by cross-reference to a dedicated data-set. Something like [this](https://github.com/mhs/world-currencies/blob/master/currencies.json) for example.

**Comment by herrniemand** [comment]
@petert82 agree

**Comment by hebrew878** [comment]
can you add language direction? ltr and rtl ?

**Comment by hebrew878** [comment]
can you add language direction? ltr and rtl ?

**Comment by pjona** [comment]
Hey,

would you be interested to add Polish translation?
I could prepare commit with data from [this list](https://gist.github.com/lukaszfiszer/7185871).

**Comment by herrniemand** [comment]
We can. But not using that list. It is mixed up. There no distinction
between official name and common name, such as
+ Rosya(Russia) - common
+ Republika Południowej Afryki(Republic of South Africa) - official

2015-08-21 12:26 GMT+12:00 Marek Skiba <notifications@github.com>:

**Comment by mledoze** [comment]
@pjona 
> would you be interested to add Polish translation?

That could be a good addition, but @herrniemand is right we will need both common and official names.

**Comment by TuningGuide** [comment]
I would like to have official and main language. For example for austria the official lang would be german and the main language would be bar.

**Comment by jhourlad** [comment]
Lovely. I would have used it if it has timezone in it.

**Comment by mledoze** [comment]
@jhourlad please read this thread https://github.com/mledoze/countries/pull/106 to see why timezones were not added in this project.

**Comment by martin-ro** [comment]
Looking https://en.wikipedia.org/wiki/Continent there is no "Oceania" continent. The JSON label says region which makes sense to call the proximate islands of Australia Oceania though its not really a continent (depending who you ask).

Would it make sense to add a continent field according to one or more of the existing continent models?

cheers

**Comment by olimortimer** [comment]
As mentioned by others, it would be useful to be able to know if a country is within the EU.

https://en.wikipedia.org/wiki/Member_state_of_the_European_Union

**Comment by mledoze** [comment]
Hello @olimortimer, yes this has been asked before by others, but unfortunately, this kind of data does not suit this project. 

Please see this comment https://github.com/mledoze/countries/issues/6#issuecomment-71026239.

**Comment by maquejp** [comment]
Hello,
About adding the cities, you can maybe see what the Eurostat is doing : http://ec.europa.eu/eurostat/web/nuts/overview

**Comment by maquejp** [comment]
**Add a format: SQL (for main AND data)**
I have done it for the main (1st draft of the data attached to this comment)
I will work on the by country files to turn them into SQL too.

[mledoze.countries.sql.zip](https://github.com/mledoze/countries/files/325694/mledoze.countries.sql.zip)

**Comment by herrjemand** [comment]
@maquejp Countries project ideology is KISS. Adding cities would majorly increase the size of the project, and would not serve according value. So I personally vote not on that idea.

About SQL DUMP: I don't see much of an issue to write a script that loads json into DB. There are far more then enough solutions online/stackoverflow. As addition it is a major security risk, to just load random sql dumps into databases. So I vote no on that one as well.

**Comment by cmacdonald** [comment]
What about the past? In using countries.json to analyse past pieces of text, I found "soviet" was not identified. Would adding a historical extension of the data with applicable dates be achievable in the long term?

**Comment by herrjemand** [comment]
@cmacdonald Countries project goal is to provide basic information about current de-jure political state of the world. We provide basic, static information.

History will never be part of this project as it is contradicts the goal of this project to provide basic and static information, and due to single case use limitation.

**Comment by mledoze** [comment]
Hello @cmacdonald, I'm sorry but historical data are out of scope for this project.

**Comment by 8alery** [comment]
Hello! I think adding emoji for country flag will be nice. You can find emoji of flags here: http://emojiflags.com/

**Comment by Bartinger** [comment]
If someone is searching for a country list with info if the country is in the EU: Here's a short script to append the info to the country list.

https://gist.github.com/Bartinger/f0507c786bad45cc942de471b1427e48

**Comment by mledoze** [comment]
@Bartinger thank you for that! :)

**Comment by pfwd** [comment]
Hi Thanks for a great project.
Are there any plans to add ISO 639-1 codes?  I'm looking for a way to adjust HTML language codes.
If the language section included the ISO 639-1 then it would be perfect for my use case.
I see that https://restcountries.eu has this support and its listed in the showcase.

**Comment by fayder** [comment]
Hi @pfwd I started restcountries.eu based on @mledoze's great data some years ago but then I started to maintain my own version. That's why they are not much similar anymore.

**Comment by marc-ed-raffalli** [comment]
Hi @mledoze, how accurate should be the country name translations? Should it be 100% or it would be ok from an online translator.

**Comment by mledoze** [comment]
> Hi @mledoze, how accurate should be the country name translations? Should it be 100% or it would be ok from an online translator.

Hello @marc-ed-raffalli, I am sorry but I don't understand your question. The translations currently available in this project were gathered from various sources (mainly from Wikipedia). I hope that they are correct but I cannot guarantee that they are 100% correct.

**Comment by marc-ed-raffalli** [comment]
Hello @mledoze, I wanted to know if the translation has to be exact or is it ok to have translation from online translator like Google Translate (which may produce inaccurate output). Then, if it is ok, what would be the list of targeted languages?

**Comment by mledoze** [comment]
Well in that case, the translations have to be exact :)

There is no list of targeted languages, any language can be added to the list of translations.

**Comment by marc-ed-raffalli** [comment]
Good to know, I'll look for better translation sources :)

**Comment by marc-ed-raffalli** [comment]
Hi @mledoze 
I found translations for a good number country names and capitals e.g. London => Londres.
In https://github.com/mledoze/countries/issues/263#issuecomment-359933770 you said planning for 2.0. I would propose to change capital to a multi dimensional array too.
```js
capital:{
en: 'London',
fr: 'Londres'
}
```

**Comment by mledoze** [comment]
> I would propose to change capital to a multi dimensional array

@marc-ed-raffalli this change was already made by @blumk in https://github.com/mledoze/countries/commit/d9e81cc083322b492c18b17faad54d5a3e4a7ff6. But translations for countries capital(s) are welcome :)

**Comment by marc-ed-raffalli** [comment]
@mledoze The change allows to support multiple capitals as an array of strings, does not allow a mapping to multiple languages. I would propose something like:
```
capital:{
  en: ['London'],
  fr: ['Londres']
}
```

**Comment by blumk** [comment]
Looking at the current `countries.json` implementation I'd suggest refactoring translations into separate *.json files, e.g. `fra.json`:
```
{
  "cca3": "ZAF",
  "name": {"official": "R\u00e9publique d'Afrique du Sud", "common": "Afrique du Sud"},
  "capital": ['Pretoria', 'Le Cap', 'Bloemfontein'],
  "demonym": "Sud-Africain"
}
```
Creating separate language files brings the following benefits:
- Current implementation has a "translations" property. Adding capitals would lead to the following confusion: translation of what? (Name, capital?). Dedicated files solves this problem (see example above)
- Languages shouln't pollute the main `countires.json` file since there are 6000+ languages. Adding a new language is difficult (see Arabic translations PR)
- You can give a single language file to a native speaker and she can confirm the correctness without knowing too much about the `countries.json` file
- Better support for lazy loading (e.g. two supported languages means loading two *.json files)

@marc-ed-raffalli @mledoze What do you guys think of this approach?

**Comment by marc-ed-raffalli** [comment]
@blumk 
> Better support for lazy loading (e.g. two supported languages means loading two *.json files)

Do you mean 3 files? one pure data (language agnostic), and two translation files

**Comment by blumk** [comment]
@marc-ed-raffalli 

> Do you mean 3 files? one pure data (language agnostic), and two translation files

Yes. Adding support for for two additional languages (`countries.json` defaults to `English`) means that you'll have to load `countries.json` and e.g. `fra.json` and `slk.json` in order to support `ENG`, `FRA`, `SLK`.

**Comment by marc-ed-raffalli** [comment]
@blumk 
I like the idea of separate language files. I would even push the idea and have all languages into dedicated files (including `ENG`) since not all apps necessarily support English :)

Let's see what's the feedback from the other contributors

**Comment by mledoze** [comment]
> Looking at the current countries.json implementation I'd suggest refactoring translations into separate *.json files

I find this idea interesting, but what would be your proposal for the directories/files structure? Given your example, would the `fra.json` file be in a `data/zaf` folder?

**Comment by blumk** [comment]
@mledoze 
> I find this idea interesting, but what would be your proposal for the directories/files structure? Given your example, would the fra.json file be in a data/zaf folder?

I guess there are two options:
- one translation file per language containing all 250 records: you can use a folder  like `data` | `translations` | `i18n` containing all translation files
- one translation file per language and record: in that case subfolders like `data/zaf` might be the way to go. However you end up having n*250 files

I might prefer one file per language containing all 250 records for the following reasons:
- it use case driven: e.g. drop down list of all countries in French, a map with all capitals in Dutch.
- one language, one location: you can give a single language file to a translator, you'll only need to load one file

**Comment by ColinH** [comment]
My suggestion on "what to add next" would be NDD and IDD prefixes.

**Comment by mledoze** [comment]
> My suggestion on "what to add next" would be NDD and IDD prefixes.

Thank your for your suggestion, I'll look into it.

**Comment by mledoze** [comment]
@blumk I would like to move forward with your proposal to refactor translations to separate files; could you please open a new issue with your proposal? Thank you very much.

**Comment by Lupinity** [comment]
One thing I would really like to see added is the most commonly used native language / administrative language used in the country.

For example, Norway has three different, unweighted native names:
`"native":{"nno":{"official":"Kongeriket Noreg","common":"Noreg"},"nob":{"official":"Kongeriket Norge","common":"Norge"},"smi":{"official":"Norgga gonagasriika","common":"Norgga"}}`

And there is no way to tell which one of the three is the commonly used, for example in language or country choosers. In this example, Norge would obviously be the way to go, not Noreg or Norgga.

Can we either have a key for the official native name or a weighted/ranked list of languages in the country?

Also, there are altSpellings:
`"altSpellings":["NO","Norge","Noreg","Kingdom of Norway","Kongeriket Norge","Kongeriket Noreg"]`

But I don't feel comfortable trusting on the first spellings to be the most common, also it's pretty much a mix of abbreviations and languages, which is generally not very helpful in this case. Also, Norgga from the native array above is missing the altSpellings, which is confusing?
