### ISSUE TITLE
Zimbabwe native language.

### ISSUE THREAD

**Issue by herrniemand** [mledoze/countries#86]
As it got to me #85 , we have an issue to resolve. According to our data native language for Zimbabwe currently is 'sn: Shona'. Officially there 16 official languages:

 - Chewa
 - Chibarwe
 - English
 - Kalanga
 - "Koisan"
 - (presumably Tsoa)
 - Nambya
 - Ndau
 - Ndebele
 - Shangani
 - Shona
 - "sign language"
 - Sotho
 - Tonga
 - Tswana
 - Venda
 - Xhosa

I propose to set English as native for now as a general medium and most neutral language in this list. And because it used in Zimbabwe public media:

 - http://www.zim.gov.zw/
 - http://www.zispa.org.zw/
 - http://www.newzimbabwe.com/
 - http://www.dailynews.co.zw/
 - https://www.newsday.co.zw/
 - etc 

Another issue is not all of this languages are defined in Zimbabwe object.

**Comment by mledoze** [comment]
When the new format for country names was introduced in v1.6, we had to choose one of the country languages for `native` names, thus the `nativeLanguage` property which identifies which one is used. 
Instead of having to do that, we could list country names in every native languages.

For example with Peru, we would have something like: 

```json
"name": {
	"common": "Peru",
	"official": "Republic of Peru",
	"native": {
		"aym": {
			"common": "Piruw",
			"official": "Piruw Suyu"
		},
		"que": {
			"common": "Piruw",
			"official": "Piruw Ripuwlika"
		},
		"spa": {
			"common": "Per\u00fa",
			"official": "Rep\u00fablica del Per\u00fa"
		}
	}
},
"...": "...",
"languages": {
	"aym": "Aymara",
	"que": "Quechua",
	"spa": "Spanish"
}
```

What do you think?

**Comment by herrniemand** [comment]
@mledoze I have not seen it. But I like the Idea.

**Comment by herrniemand** [comment]
@mledoze I will finish it by monday.

**Comment by mledoze** [comment]
@herrniemand excellent :+1:!

**Comment by herrniemand** [comment]
@mledoze How about translation?

**Comment by mledoze** [comment]
@herrniemand do you mean this https://github.com/mledoze/countries/issues/6#issuecomment-70817726?

**Comment by herrniemand** [comment]
@mledoze current translations are inconsistent with name object.

Way they are now:
```json
"translations":{
	"de" :"Russland",
}
```

The way they should be:
```json
"translations":{
	"de": {
		"common":"Russland",
		"official":"Russische Föderation"
	}...
}
```

**Comment by herrniemand** [comment]
@mledoze Yes*)

**Comment by herrniemand** [comment]
@mledoze I looked at ```countries``` commit punch card...
![screenshot from 2015-01-23 08 42 22](https://cloud.githubusercontent.com/assets/1636116/5863101/e18ed668-a2db-11e4-8f49-a63a50396eae.png)

[Friday 5pm commits...](http://devopsreactions.tumblr.com/post/98456803030/last-commit-on-friday-5pm)

![Not gut](http://media.tumblr.com/ff5c3eeb689951032d73dffaec1c413a/tumblr_inline_nbk843Svbo1raprkq.gif)

 XD

**Comment by mledoze** [comment]
yay :laughing:

**Comment by herrniemand** [comment]
@mledoze I think we finally solved that issue, so its can be closed.

**Comment by mledoze** [comment]
@herrniemand yes indeed!
