### ISSUE TITLE
Proposal: remove some entries

### ISSUE THREAD

**Issue by mledoze** [mledoze/countries#93]
After further thinking about #57 and #77, I would like to propose the removal of the following entries, so that each entry in the dataset represent only one entity:

- `Saint Helena, Ascension and Tristan da Cunha` (group of islands)
- `Bonaire` 

`Bonaire` for example, share the same ISO codes as `Sint Eustatius` and `Saba` (which are not listed). The same goes for the three islands of `Saint Helena, Ascension and Tristan da Cunha`.

Let me know what you think.
Thank you.

Edit: removed `South Georgia and the South Sandwich Islands`, `United States Minor Outlying Islands` and `Svalbard and Jan Mayen`.

**Comment by mledoze** [comment]
@herrniemand nothing. I edited my first https://github.com/mledoze/countries/issues/93#issue-52601329.

**Comment by herrniemand** [comment]
@mledoze Ok. I see *)

**Comment by herrniemand** [comment]
@mledoze How do you reference specific comment?

**Comment by mledoze** [comment]
You just have to commit its SHA-1 hash, like so 8ec9d7a52c8df1366b8fce7650963b6361ca522d

**Comment by herrniemand** [comment]
@mledoze I mean actual `message/comment` in the discussion, like you've done previously.

**Comment by herrniemand** [comment]
@mledoze 
```
@herrniemand nothing. I edited my first #93 (comment).
```

**Comment by mledoze** [comment]
Select text, then press `r`. More info https://github.com/blog/1399-quick-quotes.

**Comment by herrniemand** [comment]
> Select text, then press r. More info https://github.com/blog/1399-quick-quotes.

Testing

**Comment by herrniemand** [comment]
@mledoze Found it [LOL](https://github.com/mledoze/countries/issues/93#issuecomment-71624145)
