### ISSUE TITLE
Export tags to packgist

### ISSUE THREAD

**Issue by moffe42** [mledoze/countries#98]
It would be great to be able to check a specific tag out with composer. Ie. export the tags to packagist.org.

This way it is easier to manage dependencies, instead of getting dev master.

**Comment by mledoze** [comment]
@moffe42 yes no problem, but I'm a bit new to packagist. Do you know how to do that?

**Comment by mledoze** [comment]
I just run the command `composer show -v mledoze/countries`, here is the result:
```
Reading composer.json of mledoze/countries (v1.6)
Skipped tag v1.6, no composer file
Reading composer.json of mledoze/countries (v1.5.1)
Skipped tag v1.5.1, no composer file
Reading composer.json of mledoze/countries (v1.5)
Skipped tag v1.5, no composer file
Reading composer.json of mledoze/countries (v1.4)
Skipped tag v1.4, no composer file
Reading composer.json of mledoze/countries (v1.3)
Skipped tag v1.3, no composer file
Reading composer.json of mledoze/countries (v1.2)
Skipped tag v1.2, no composer file
Reading composer.json of mledoze/countries (v1.1)
Skipped tag v1.1, no composer file
Reading composer.json of mledoze/countries (v1.0)
Skipped tag v1.0, no composer file
Reading composer.json of mledoze/countries (master)
Importing branch master (dev-master)
name     : mledoze/countries
descrip. : World countries in JSON, CSV and XML.
keywords : world, countries, json, csv, xml
versions : dev-master
type     : library
license  : Open Database License
source   : [git] https://github.com/mledoze/countries.git 0c88826a6ecaf32529e2c62bc3a5f448b284c4f5
dist     : [zip] https://github.com/mledoze/countries/archive/master.zip
names    : mledoze/countries

support
source : https://github.com/mledoze/countries/tree/master
issues : https://github.com/mledoze/countries/issues

requires
php >=5.4
symfony/yaml 2.6.1
```

**Comment by shehi** [comment]
@mledoze : Please refer to this page for how to create versions for packages in Composer:
https://getcomposer.org/doc/02-libraries.md
To learn more about tagging in Git, check here or countless other resources: http://git-scm.com/book/en/v2/Git-Basics-Tagging

In nutshell, after you have created your Packagist.org account, you will submit your package (git repo) to it. Packagist will checkout the project with all its tags and list them there. Feel free to tag your repo and try and learn - it's easy :) Good luck!

**Comment by moffe42** [comment]
Sorry @mledoze have no experience with packagist as a package maintainer, only consumer.

But as far as I can see, when you start tagging in Github and there is a composer.json present, it should run more or less by it self. You might need to check up on the composer.json content, but that should be fairly easy, given the link from @shehi.

**Comment by mledoze** [comment]
@moffe42 I'm going to publish a new release so that the latest tag contains a `composer.json` file.

**Comment by mledoze** [comment]
With the latest release v1.6.1, Packagist now show it along with `dev-master`.
