### ISSUE TITLE
Flag aspect ratio

### ISSUE THREAD

**Issue by calvintennant** [mledoze/countries#99]
It doesn't look like the aspect ratio of your flags are correct.

See: http://en.wikipedia.org/wiki/List_of_countries_by_proportions_of_national_flags

**Comment by herrniemand** [comment]
Thanks @calvintennant. I will try fix it by Monday.

**Comment by mledoze** [comment]
@herrniemand thank you for taking care of that.

**Comment by herrniemand** [comment]
@mledoze @calvintennant  #100  nya*) :shipit:

**Comment by herrniemand** [comment]
@mledoze I think this issue can be closed
